### ISSUE TITLE
Appearance: Saving manager config causing empty file, breaking UI

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1036]
**Describe the bug**
Saving changes to the manager_config file, sometimes breaks the Manager UI.
There seems to be a case where an empty object `{}` gets saved instead of the normal manager config fields.

**To Reproduce**
No clear idea what causes this issue. @pierrekil and @DonWillems should look into this on how to reproduce it.
The information I got is:
1. Go to the appearance page
2. Edit some properties in either the "Realm styling" or the "Map settings".
3. Press the save button
4. `manager_config.json` only has `{}` as content. (an empty object)
5. As a result the map is dissapears and "Map settings" doesn't show available realms anymore 

**QUESTION**
@MartinaeyNL can it have to do with only those projects for which the map is located at our own map server?

See also #1056

**Comment by pierrekil** [comment]
@Martin can you check the above question?

**Comment by MartinaeyNL** [comment]
To reply on @pierrekil question:
*"can it have to do with only those projects for which the map is located at our own map server?"*

Yes it could, but I __think__ I also was able to reproduce it locally.
If it only happens on deployments, making it likely to be a pathing issue, it should happen on __every__ save.

When diving into this issue, the process of saving the file looks fairly straightforward.
And it does make changes to the file; it modifies the content to an empty `{}` object.
That would mean that the issue ain't backend related.

An frontend issue where the ManagerConfig object is incorrectly modified is way more likely.
It should appear as an error in your browsers console as well, which would make identifying more easy.
