### ISSUE TITLE
Insights: page refresh 'crashes' tab

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1050]
Reproduce:
- Switch between insights pages a few times and refresh
- Page is stuck in 'loading' and GET for /master/dashboards/all/master is not finished:
![image](https://user-images.githubusercontent.com/14177035/235461765-c6e31c05-8b1b-4c45-9ae5-1efbeb0d3b3d.png)

Initially seemed related to #1049 but is also reproduced without the dialog showing up. However, if encountering the dialog, pressing discard, and refreshing, this issue will appear too.

**Comment by MartinaeyNL** [comment]
I have been able to reproduce the bug here. Don't know the exact cause yet, but I can confirm that the crashes are caused by
an infinite loop of UI updates triggered by Lit. Will be working on a fix right away.
