### ISSUE TITLE
Public dashboard not showing attributes for all widget types

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1057]
When creating a public dashboard and making asset/attributes on that dashboard public read/write:
- [x] chart widget still indicate: No attribute(s) connected.
- [x] map widget doesn't show assets and attributes
- [x] KPI widget only shows value but no graph

**Comment by MartinaeyNL** [comment]
Solved. Will be fixed in #1054 . Ready on a deployment for testing.
