### ISSUE TITLE
Image Widget Improvements

### ISSUE THREAD

**Issue by mihaelaaleks** [openremote/openremote#1074]
Improvements to be done to Image Widget v2:

- Remove local image upload widget settings section - replace with web URL image upload 
- Display the current saved URL
- Add assets to attribute marker labels
- Remove number input from marker coordinate sliders
- Add units to markers

**Comment by pierrekil** [comment]
- when adding another attribute, the attribute picker displays the selected attribute(s) from the previously added first attributes:
![Screenshot 2023-06-19 at 13 40 53](https://github.com/openremote/openremote/assets/11444149/175af648-f84f-4d7e-aa2e-699af652ac58)

**Comment by mihaelaaleks** [comment]
Widget Improvements:

- [ ] Remove local image upload widget settings section - replace with web URL image upload
- [ ] Display the current saved URL
- [ ] Add assets to attribute marker labels
- [ ] Remove number input from marker coordinate sliders
- [ ] Add units to markers
- [ ] Fix marker coordinate ordering to match attribute list
- [ ] Give markers default values
- [ ] Fix markers jumping to correct position on reload
- [ ] Implement marker changing position fluidly with slider movement
