### ISSUE TITLE
Login: Title Bar Text Glitch Issue

### ISSUE THREAD

**Issue by kpin404** [openremote/openremote#1096]
Hello Openremote Support Team, I have noticed one thing strange that it still shows `Openremote Demo` Title text every time in the browser's window for 1-2  seconds while loading the login and logout pages even after customizing and changing the title text. I have tried to look into the` login.ftl` file, but didn’t get any title text named `Openremote Demo`. Where this glitch comes from actually and try to fix this bug please? Herein the screen shot for this. Thanks.
![openremoteScreenshot_129](https://github.com/openremote/openremote/assets/86216045/b47fa9f5-01d6-4c70-830a-b976bc55692b)

**Comment by richturner** [comment]
Hi,

Thanks for reporting.

@DonWillems this is likely caused by the `<title>OpenRemote Demo</title>` tag in `manager/index.html` this should be removed and let the javascript set the title based on config

**Comment by kpin404** [comment]
Hello @richturner  Thank you for your prompt response on the flagged issue.  I appreciated it. 

But, sorry to say that I didn’t get any such file named `index.html` in any of the folders, which all are created and working under deployment folder. Please review the folder tree structure for this openremote deployment. Thanking you.
![openremoteScreenshot_130](https://github.com/openremote/openremote/assets/86216045/db4c2e1b-5035-419b-bba7-7be2aeba3c4b)

**Comment by richturner** [comment]
Should be resolved
