### ISSUE TITLE
Update Android apps

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1104]
Update the following apps to target the latest Android version: OpenRemote and Beatrixkanaal

**Comment by Miggets7** [comment]
@richturner for Beatrixkanaal I would need to update the OR branch in order to resolve some android issues. Is it fine to update to the latest master?

**Comment by Miggets7** [comment]
@richturner is it ok to update to latest master?

**Comment by richturner** [comment]
Shouldn't mention specific projects in main repo...

@Miggets7 I've now updated the ein****** repo to the latest openremote submodule so feel free to do what you need to on the Android/iOS apps in there
