### ISSUE TITLE
Apps list in custom projects includes an "images" option.

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1116]
When using the consoles, and having the 'app selection' menu, it will have an unknown 'images' option.
Tested on several projects with this result:
```
GET http://localhost:8080/api/master/apps
[
  "insights",
  "manager",
  "images",
  "... any custom apps"
]
```

Also worth noting;
I did not find a way to disable platform apps like 'insights' and 'manager' for custom projects.
Since the apps are located in a submodule, you cannot add an `.appignore` file to disable them.
Might be worth a look.

**Comment by richturner** [comment]
Documentation is still lacking for this but the logic described in the various issues captured in #925 should work; .appignore can be added to the source code of custom directories that end up in the `CUSTOM_APP_DOCROOT` but also the `console_config.json` can be used

**Comment by richturner** [comment]
Closing this unless there is a specific bug with implemented functionality

**Comment by MartinaeyNL** [comment]
Thanks! I wasn't aware the `console_config.json` existed and what it did. Solved the problem I had.
I agree that documentation, or reference to it, should be added indeed.
