### ISSUE TITLE
Insights: refresh option to enable periodic data updates

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1120]
As an insights page user I want to have a page open for an extended period and see 'live' data, so that I don't have to refresh the page manually and keep it running on a screen.

Add option on the insights page in view mode to enable period data updates. For widgets with time period presets selected, those should be updated for 'now'. 

Available data fetch times (for now): 1 min, 5 min, 15 min, 1 hour.

mockup to be added

Question:
- Should this setting be in url? So when you share it is automatically set to that refresh timer.

**Comment by pierrekil** [comment]
- [ ] Map is not visible as widget on standalone dashboard
- [ ] Apply refresh options also on standalone dashboard
- [ ] Do not show settings (upper right) when no dashboard is selected:
![Screenshot 2023-11-13 at 15 12 50](https://github.com/openremote/openremote/assets/11444149/f8b995ff-d377-4f96-8b15-b556db316c19)
