### ISSUE TITLE
Logs: add rule ID to its log messages so that can be used for filtering and searching

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1126]
As a integrator I want to easily see log messages from the rule I am developing, so that my workflow and speed improves.

- Add rule ID as prefix to log message
- Make these log message easily viewable from rules UI.

Designs to be added

**Comment by richturner** [comment]
#836 Seems to also describe this issue

**Comment by richturner** [comment]
Bigger rules UI should be incorporated into #569
