### ISSUE TITLE
Document: Groovy example Sum a group

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1127]
Add a Groovy example for summing children of a parent, similar as for control a group example: https://github.com/openremote/openremote/wiki/User-Guide%3A-Create-Rules-with-Groovy-Editor#example-groovy-rules

**Comment by DonWillems** [comment]
Thats done here I think: https://docs.openremote.io/docs/user-guide/rules-and-forecasting/groovy-rules/#example-groovy-rules
