### ISSUE TITLE
Parse Custom Teltonika Parameters (Not in AVL list)

### ISSUE THREAD

**Issue by pankalog** [openremote/openremote#1138]
The plan is to ask Teltonika directly about the meaning of all those parameters after updating them on the project's progress.

**Comment by pankalog** [comment]
Using https://github.com/TimeLord2010/TeltonikaParser, we could assume the following:

- `pr`: priority of sent packet (see below)
- `alt`: current altitude 
- `ang`: current angle
- `sat`: number of fixed satellites
- `sp`: current vehicle speed, which I am guessing uses the configured speed source (OBD, GNSS, or accelerometer?)
- `evt`: parameters that are raising an event.

https://wiki.teltonika-gps.com/view/Codec Maybe reading here would be more useful, especially for priority. Here's what Teltonika has to say about it:

```
Altitude – meters above sea level.
Angle – degrees from north pole.
Satellites – number of visible satellites.
Speed – speed calculated from satellites.
```

```
Note: If record are without valid coordinates – (there were no GPS fix in the moment of data acquisition) – Longitude, Latitude and Altitude values are last valid fix, and Angle, Satellites and Speed are 0.
```

So, in the Handler, I should probably check if `ang` is zero, and then go on from there.

Would these parameters be okay enough to set as default for the attribute?

**Comment by richturner** [comment]
@pankalog Please migrate to fleet management repo
