### ISSUE TITLE
Customize Widgets in Insight Section

### ISSUE THREAD

**Issue by BabutaAniket** [openremote/openremote#1180]
Hello team,

Currently there are limited number of widgets (Line, KPI, Gauge, Map, Image) with which we can create a dashboard. 
Is there any way to customize widgets in insights section and add more functionality? Can we do this in the custom project repo? 

Thanks & Regards,
Aniket Babuta

**Comment by pierrekil** [comment]
Hi Aniket, this is a question for our https:/forum.openremote.io Please post there.
