### ISSUE TITLE
OR widget enhancements

### ISSUE THREAD

**Issue by echostorm** [openremote/openremote#1186]
Is there any repo or marketplace for extra widgets to use with OR insights dashboard? The current offering is very limited! For example, I can't find a diverse option for charts like bars and pie etc I would expect something like Apex charts would always be supported fully in an IOT dashboard, another is labelling, embedding widget, adding video, data tables etc.

Further, a very important requirement would be sending commands to IOT device that would require buttons and on/off selectors, which I can't find any option to implement.

Can you please advise me if this functionality is not available, how I would implement it?
I'm working with LoRaWAN devices and connecting to LNS with MQTT, so I need to have both uplink and downlink ability in dashboard.

**Comment by pierrekil** [comment]
Hi, this is a question for our forum. FYI, we are 100% open source, so we welcome contributions: https://github.com/openremote/openremote/wiki/Developer-Guide%3A-Widget-customization-on-Insights
Secondly, more widgets are coming, like table, controls and more flexible time settings. Please comment and share your wishes (or contributions) on https://forum.openremote.io/
