### ISSUE TITLE
Attribute input: input is automatically rounded to 3 decimals by default

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1187]
Reproduce:
1. In the manager write a value like 3,9032847 to a number input.
2. It will write it(?)/show it as 3,903

Expected:
2. To be able to write as many decimals as you like by default. If a limit is desirable, it can be set with the Format configuration item.

**Comment by MartinaeyNL** [comment]
Hi @DonWillems @richturner ,

Within the manager we format every number value to a localized format using `Intl.numberFormat()`
Based on the [JavsScript spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#maximumfractiondigits), by default it will to fallback to 3 digits unless configured differently.
This is why you see it "jumping" after pressing ENTER on number inputs 😉 

It already takes the `format` MetaItem into count.

What do we want to adjust here?

**Comment by DonWillems** [comment]
It doesn't fit our application to set it to 3 by default. Could we overwrite this with our own default of 'no limit'? And then users can overwrite that with format.

**Comment by DonWillems** [comment]
@MartinaeyNL whats the status of this one?
