### ISSUE TITLE
iOS App: user has to log in every time they open the app

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1193]
A user has to log in every time they use the app.
On Android the session token with a duration set to e.g. a week, keeps the user logged in after closing and opening the app.
On iOS this does not work.

What is missing on the iOS side?
What should be fixed to properly keep a user logged in for x days after they close the app?

**Comment by bitmorse** [comment]
I've noticed this issue as well, however this is an issue with the realm property "rememberMe" set to false by default. 
If you use e.g. Swagger to create a new realm directly via REST api, you can use this body to set that rememberMe param to true:

 {
  "name": "YOURREALMNAME",
  "displayName": "YOUR REALM NAME,
  "enabled": true,
  "notBefore": 0,
  "resetPasswordAllowed": true,
  "duplicateEmailsAllowed": false,
  "rememberMe": true,
  "registrationAllowed": false,
  "registrationEmailAsUsername": false,
  "verifyEmail": false,
  "loginWithEmail": true,
  "loginTheme": "openremote",
  "accountTheme": "openremote",
  "adminTheme": "openremote",
  "emailTheme": "openremote",
  "accessTokenLifespan": 0
}


This then shows the "Remember Me" checkbox in the UI upon login. If that is checked by the user, then the iOS app will remember via a cookie and you can close and open the app. Test via my iPhone after force closing the OpenRemote app from the App Store.

**Comment by MartinaeyNL** [comment]
Just to clarify here;

Checking the Keycloak 'remember me' button upon login, saves the credentials in persistent cookies.
In case of our iOS console this seems to be persisted when reopening the app, on Android it does not.
We've done some changes to the consoles (don't know exactly what) to fix this, but not sure whether these helped.

So yes this functionality @bitmorse implemented will help, but is not the solution to the problem mentioned in this issue 😉
