### ISSUE TITLE
Alarms: list of improvements

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1210]
General:
- [x] Alarms icon should change to color 4 when the badge is present

Alarms page:
- [x] Delete icon should only be shown when a checkbox is checked. It should appear on the left of the sorting options. A subtle vertical line between them would be nice.

- [X] Change alarms icon to the one used in the header (and give the same margin as the next item in this list)
- [X] 20px margin to sides of table
- [X] Set 10px top and bottom margin on the whole top element of the page so you can nicely align everything vertically (so remove the margin from the filter dropdowns)

- Table:
- [X] Sorting is not working
- [X] Remove 'severity' header and give column width of the icon
- [X] Give status max with of 'acknowledged' pill
- [X] Give last modified max width
- [X] Give all remaining with to title
- [x] Default should show 100 items of the pagination options
- [X] Order: checkbox, severity, title, status, assignee, updated on
- [x] Add asset to table for widescreen
- [X] Severity filter should have: All (default), high, medium, low
- [X] Status filter should have: All active (default), All, [all states]

Single alarm page:
- [X] Assignee dropdown does not show current assignee 
- [x] - Show source of alarm in the column of fields on the right
- [x] - Make creation and update fields readonly/disabled so that they don't give green underline on click
- [x] In the breadcrumb, use the alarm id instead of the title
- [X] Align title and breadcrumb with panel (same as users page. Lets see how weird it is if the title is not in the same page as alarms page)

Notifications:
- [ ] Severity high should send email to assignee of an alarm on creation, and on it being assigned (? will this be annoying if you assign it to yourself as admin). If the alarm does not have an assignee on creation, the email should go to all users with write access to alarms.

-

**Comment by pierrekil** [comment]
- [ ] When selecting/unselecting an alarm, the status columns shifts to the right, see below
![Screenshot 2024-02-29 at 08 51 17](https://github.com/openremote/openremote/assets/11444149/958d5b66-5900-41b3-b08f-c1772f338751)
![Screenshot 2024-02-29 at 08 51 25](https://github.com/openremote/openremote/assets/11444149/9fe1c284-dbec-4989-96ac-77c80928491f)
- [ ] The 'overall' toggle doesn't respond correctly to status of individual rules. Reproduce: try (un)selecting individual rules as well as overall toggle. See below
![Screenshot 2024-02-29 at 14 13 03](https://github.com/openremote/openremote/assets/11444149/0dd5fa62-5ce8-41e6-aac4-964fc915a06e)
- [ ] If you select status 'open' issues (when there are none with that status) the selected status doesn't show. See below
![Screenshot 2024-02-29 at 08 54 04](https://github.com/openremote/openremote/assets/11444149/cee95a4f-35a2-4ae9-9460-608b4af83552)
- [ ] Delete alarm modal doesn't show friendly text, see below
![Screenshot 2024-02-29 at 08 55 01](https://github.com/openremote/openremote/assets/11444149/1768b60b-2333-402b-9f2d-8422c5921284)
- [ ] Delete button doesn't show correctly, see below 
![Screenshot 2024-02-29 at 14 19 02](https://github.com/openremote/openremote/assets/11444149/83c45530-cd0c-4de4-9ee1-ea006faa0dce)

**Comment by pierrekil** [comment]
Closed as replaced by #1250
