### ISSUE TITLE
Insights: translations of settings

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1215]
Translations of some setting of the widgets are not give, currently cameCase
<img width="297" alt="Screenshot 2023-12-23 at 09 59 59" src="https://github.com/openremote/openremote/assets/11444149/54ef58bb-9cdb-47e6-bd22-0591db5e56db">
<img width="299" alt="Screenshot 2023-12-23 at 10 00 09" src="https://github.com/openremote/openremote/assets/11444149/902274d9-ad8f-4533-927f-2d461cd21dc0">

**Comment by DonWillems** [comment]
I will pick this up in my translation work

**Comment by DonWillems** [comment]
Also, this seems like some sort of caching issue? I can't reproduce it.
