### ISSUE TITLE
Add remember me to realm creation page

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1228]
When adding a new realm or changing an existing one, I want the option to show the 'remember me' option

See forum: https://github.com/openremote/openremote/issues/1193#issuecomment-1902636147

**Comment by bitmorse** [comment]
I submitted a pull request for this (#1227 )

**Comment by pierrekil** [comment]
Hi Sam, thanks for helping out! For contributions we are requesting to sign a contributor license agreement first. Could you drop us an email at info@openremote.io so we can send you one? Thanks!
