### ISSUE TITLE
OR Core (UI): Add flexible keycloak interval

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1233]
**Problem**
Currently, we use a 30 second interval in our frontend apps to refresh the Keycloak access token.
From there, the keycloakJS library handles the processing of storing the token.
In case of Keycloak being configured differently, we do not want this 30 second interval.

It should adapt to the settings in Keycloak.

.
See the current code here:
```typescript
protected async updateKeycloakAccessToken(): Promise<boolean | void> {

        // Access token must be good for X more seconds, should be half of Constants.ACCESS_TOKEN_LIFESPAN_SECONDS
        const promise = this._keycloak!.updateToken(30) as Promise<boolean>;
        promise.then(tokenRefreshed => {
            console.debug("Access token update success, refreshed from server: " + tokenRefreshed);
        }).catch(() => {
            console.error("Access token update failed.");
            this._setAuthDisconnected(true);
        });
}
```

**Comment by richturner** [comment]
This call only refreshes the token if it expires within the next 30s so this isn't dependent on how long the token is valid for
