### ISSUE TITLE
Alarms: list of bugs and improvements

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1250]
Bugs:
- [x] User can create empty alarm
- [x] User can switch to any source when creating an alarm manually
- [x] Date time Modified shown when creating an alarm
- [x] When sorting an empty table an error occurs
- [x] Clicking the 'select all' checkmark results in an error
- [x] Save button is enabled even if nothing changed when opening an existing alarm
- [x] Sorting leads to error : This `ChildPart` has no `parentNode` and therefore cannot accept a value. This likely means the element 
- [x] containing the part was manipulated in an unsupported way outside of Lit's control such that the part's marker nodes were ejected from DOM. For example, setting the element's `innerHTML` or `textContent` can do this.
- [x] When selecting an alarm on an asset page, the alarm opens. If afterwards the 'assets' tab is slected it opens the alarms overview page

**Comment by pierrekil** [comment]
Lat item still open, and added few more:
- [ ] When selecting an alarm on an asset page, the alarm opens. If afterwards the 'assets', 'rules' or 'map' tab is selected it opens the alarms overview page
- [ ] Select 'assigned to me' an create a new alarm. It shows all alarms although 'assigned to me' is still enabled
- [ ] Select one alarm with toggle on the left, select 'Assigned to me': overall selection shows 'V'; when unselecting 'Assigned to me' non of the alarms is selected but overal selection shows '-'.
- [ ] When sorting alarms, they are ordered in alphabetical order. You'ld expect ordering by step in the process. Add a number to the status to resolve if an alternative is not feasible (hidden character?)
- [ ] When an alarm page is open, switch realm. Alarm is still shown and you can also save it. Expected: show alarm list of selected realm or empty page
- [ ]

**Comment by pierrekil** [comment]
Still working on the last item?

**Comment by DonWillems** [comment]
- [ ] When entering the page, the table sorting indicates it sorts by severity, but it doesn't. Its sorted by updated date, which is fine, but it should indicate that. So, by default sort by updated, and indicate that that is the case.

TBC

**Comment by MartinaeyNL** [comment]
@pierrekil asked me to review the PR, so will do that right away.

**Comment by MartinaeyNL** [comment]
Put a review down addressing some technical topics that need some work.

@DonWillems as this is more styling related it's up to you whether to close this issue or not.

**Comment by wborn** [comment]
I think everything in this issue got addressed.

What has not been fully addressed is tracked by:

* https://github.com/openremote/openremote/issues/1312
* https://github.com/openremote/openremote/issues/1313
