### ISSUE TITLE
Broken manager account page

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1255]
- [ ] Change account page by the regular user page
- [ ] Don't show header 'users -> name'
- [ ] Check if/how authenticator functionaliuty can be preserved

**Comment by pierrekil** [comment]
Add mobile authenticator set up page from keycloak and take care that when submitting, users are redirected back to user page.

**Comment by MartinaeyNL** [comment]
What do you think of this @pierrekil @DonWillems 

![Image](https://github.com/user-attachments/assets/c426e134-2cb5-4a6a-ae88-855e2b8f2af3)

**Comment by MartinaeyNL** [comment]
Discussed the UI with @DonWillems and he is happy with the changes.
The PR is ready for a technical review.
