### ISSUE TITLE
Insights: Thresholds not working for booleans (on off)

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1262]
Try with onOff of Lights

**Comment by MartinaeyNL** [comment]
Should the Gauge widget be able to work with booleans?

**Comment by pierrekil** [comment]
Don't see much value for that, map, table, attribute: yes. Which widget is this referring to?

**Comment by MartinaeyNL** [comment]
Just discussed it with @DonWillems, he is referring to the Map widget.
I am able to reproduce it, simply by making a map and selecting a boolean attribute.

Put the issue in the backlog for now, you can choose whether to pick it up in a sprint.
