### ISSUE TITLE
Demo '/main' - Mobile

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#128]
- [x] Icon on screen white background (now black on iOS), names: 'Demo Building' and 'Demo City' 
- [x] on Asset view page: hide 'info' widget, 'Assets' as first widget, 'History' as 2nd, 'Map' as 3rd

**Comment by robin-dekkers** [comment]
Names cannot be changed. The file containing the name of the app is static (app/main/index.html).

**Comment by pierrekil** [comment]
Can background be changed from black into white?

**Comment by robin-dekkers** [comment]
Yes, i have already changed the color to white.

**Comment by pierrekil** [comment]
Android is white but iOS still black

**Comment by pierrekil** [comment]
This is fixed on EMS, but does it get through on Main branch?
