### ISSUE TITLE
Improve backend APIs of alarms functionality

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1311]
As noted in the PR #1244, there are several topics to address in regards to the backend (REST) APIs.
Think of authorized access of alarms, error handling, and improving the code quality for future enhancements.

Please take a look at the comments in the PR for more details, and address them.

**Comment by wborn** [comment]
I already addressed many of your comments. Can you have another look to see if you agree with the changes and check if new issues got introduced?
