### ISSUE TITLE
Alarms: icon in header does not show badge for realm user

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1314]
Reproduce:
- Log in as user to a realm (with permissions to view alarms)
- Make sure there is an alarm that is open and assigned to that user
- See that the icon does not show a 'badge' in the top right of it indicating there is an open alarm for you

![Image](https://github.com/openremote/openremote/assets/14177035/c64de983-2f54-494c-a048-785527948c14)

Expected:
- If an open alarm is assigned to you, be notified by icon in header with color and 'badge'

![Image](https://github.com/openremote/openremote/assets/14177035/e3693455-e4f4-469a-bb70-ef456badbed3)

**Comment by wborn** [comment]
This should work with the commits pushed today.
