### ISSUE TITLE
Syntax for dynamic time HTTP Agent

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1321]
Allow users of the HTTP Agent to add a dynamic start/end time to Agent/Attribute link

**Comment by richturner** [comment]
Some APIs require absolute timestamps on query parameters for example so it should be possible to use some syntax to allow dynamic query parameter values similar to the `DYNAMIC_VALUE_PLACEHOLDER` `{$value}` replacement.

Syntax:
```
${time:DURATION:FORMAT}
```

* DURATION - ISO8601 Duration
* FORMAT - Maybe use java simple date format (https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) with some option for epochSeconds and epochMillis

Examples:
```
now()-1min = {$time:now-PT1M} or {$time:-PT1M}
now()+1hour = {$time:now+PT1H} or {$time:+PT1H}
now() = ${time}
```

**Comment by richturner** [comment]
See #1374

**Comment by richturner** [comment]
@pankalog For polling requests see:

`HTTPProtocol.HttpClientRequest` which currently handles dynamic value injection into polling requests.
