### ISSUE TITLE
PostgreSQL: Timescale configuration has not run for all deployments

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1322]
The staging.re****** and staging.vd*-** databases did not have the timescale DB optimized configuration, while they were created after the addition of the plugin.

It is unclear why the script for configuration was not executed.

**Comment by MartinaeyNL** [comment]
Closed a duplicate issue, continuing on this one.

To give a bit more context on the technical side;

**Problem:**
On several instances we've seen the `timescaledb-tune` script **not** being run on initialization / startup.
So, the default PostgreSQL configuration is used instead, causing performance issues on medium to large datapoint tables.

**How to fix:**
Investigate existing instances, and check the setup / migration functions to see whether `timescaledb-tune` ran correctly.

Documentation on timescaledb-tune;
https://docs.timescale.com/self-hosted/latest/tooling/about-timescaledb-tune
