### ISSUE TITLE
OTP login: adjust layout to show radio button when selecting 2FA device

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1386]
Currently its not clear there is a radio button above the field where you enter the 2FA code:

![Image](https://github.com/user-attachments/assets/a0ad27a7-07af-40e1-af07-2ca06ed85a8b)

When changing the css you can see its actually a radio button:

![Image](https://github.com/user-attachments/assets/65dccaa6-775f-4706-bdb2-a4428a45c550)

- List the devices above each other
- Give the list a header: "Select your authenticator device:"
- Be able to set color of radio buttons

**Comment by MartinaeyNL** [comment]
Merged with this PR in the keycloak repository;
https://github.com/openremote/keycloak/pull/4
