### ISSUE TITLE
Edge Gateway

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#139]
- [x] Replicate manager on 8GB Odroid C2 
- [x] Replace Acc. mgt. and ID service
- [x] Connect to manager as cloud coordinator of multiple edge gateways as assets within a realm
- [x] Synchronise assets and attributes, only editing allowed when connected; no edge gateway rules visible on cloud coordinator, only realm rules

**Comment by DonWillems** [comment]
![3_Mioto_Assets copy 3](https://user-images.githubusercontent.com/14177035/76457575-58609880-63d9-11ea-9587-769199522dc0.png)
![5_Mioto_Assets copy 4](https://user-images.githubusercontent.com/14177035/76457578-5991c580-63d9-11ea-8875-d7f2e5a88eee.png)

**Comment by richturner** [comment]
Implemented by 352a3e5703f5956139ea7be7c7ae429aa77a34e7
