### ISSUE TITLE
Build deployment pipeline

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#14]
- [ ] Pick provider for container hosting

- [ ] Kubernetes orchestration of images, containers, configuration data 

- [ ] Install service (Jenkins?) for automated build and integration test of all targets triggered by Github push event, configuration through files in repositories

- [ ] Evaluate all-in-one solutions like fabric8, Rancher because it has cluster node image for rpi3, must provide Docker Registry for private images

Deployment targets:

- [ ] Raspberry Pi 3
- [ ] Any x86 Docker host
- [ ] AWS and GKE

**Comment by christianbauer** [comment]
This is a build setup for rpi images with Docker support: https://github.com/hypriot/image-builder-rpi

A VirtualBox Ubuntu x86 machine with Docker runs QEMU to get the ARM platform.

**Comment by aktur** [comment]
This issue can be closed. We've gone different path anyway.
