### ISSUE TITLE
Notifications: Add option to set multiple languages for the notifications

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1401]
As a user I want to set multiple languages for notifications I sent using When-Then rules, so that end users get the notification in their preferred language.

User attribute:
- Store the preferred language of a user against a user attribute. This language comes from the phone browser language, and later from the user preferred language as selected in the app.
- Should we also store it in an attribute of the console? If a user account is used by multiple people, they could still have their own language set in this case. When sending a notification the system would first check if there is a language set in the console, if not, use the language set on the user account.

Manager_config.json and appearance page:
- Set the languages that should be available for notifications localization.
- Set the default language if the user's language is not present.
- Multi-select dropdown that shows selected languages
- Select dropdown to set a language from the previously selected languages as default. (if the language that is currently default is removed from the list above, set the first language in the list as new default)
![Image](https://github.com/user-attachments/assets/77765c22-9213-4296-83e9-e71aa677ca9e)

Manager UI, When-Then rule:
- Add a select field in the dialog to switch between languages if more than one is set in the manager config OR if the particular JSON rule already has multiple languages (so even if its not in the manager config, it should show the dropdown for that rule). All fields can be different per language. The default language is shown when the dialog is opened.
- When switching to a different language, all fields except title and content are already filled with the contents of the default page. All can be overwritten.
- When a languages isn't fully set, indicate with a red number icon next to the language field. On hover (in the title of the icon) you can see which languages are not set.
- Or if they are not set at all, does it just fall back to the default? Should it be a warning, not an error? Everything that is not filled in just uses default?
![Image](https://github.com/user-attachments/assets/391b5fb9-d557-4868-b038-d8109b834bac)

JSON rule and notification handler:
- Should add language to their structure for email and push notifications
- Should be backwards compatible, if there is not language in the JSON, it should just use default
- This would be implemented in the notification message and the notification handlers will need to understand it and deal with language preference lookup.

Open questions:
- Should the manager also keep track of preferred language of user?
- Should the user page and account page show preferred language?

**Comment by richturner** [comment]
Notification language options don't belong in the manager_config....this is intended for the manager UI app notifications are a backend thing not related to the manager UI app.

I guess this is to avoid free string for language(s) on the push notification dialog and we don't have a notifications page.

If an existing rule is modified what should happen to push notification languages that are defined but the `manager_config` no longer includes that language, should they be deleted?

**Comment by richturner** [comment]
Backend user language preference could make use of keycloaks internationalization, when this is enabled then users can have a language preference and we could expose this in the user object

**Comment by DonWillems** [comment]
> Notification language options don't belong in the manager_config....this is intended for the manager UI app notifications are a backend thing not related to the manager UI app.
> 
> I guess this is to avoid free string for language(s) on the push notification dialog and we don't have a notifications page.
> 
> If an existing rule is modified what should happen to push notification languages that are defined but the `manager_config` no longer includes that language, should they be deleted?

Its meant as a manager UI thing indeed. With that option in the manager config, you make it available in the dialog on the When-Then rules. Technically this translates it to the proper JSON rule to send the notifications. So it has no impact on the backend in that sense. The JSON is still interpreted based on the languages set in there, whether that is done through the Manager UI app or in some other way.

I think if a language is removed from the manager config, but was set before in the When-Then UI, it should remain in the JSON. Maybe that part of the JSON should be available from the dialog,... switching trains

**Comment by DonWillems** [comment]
> Notification language options don't belong in the manager_config....this is intended for the manager UI app notifications are a backend thing not related to the manager UI app.
> 
> I guess this is to avoid free string for language(s) on the push notification dialog and we don't have a notifications page.
> 
> If an existing rule is modified what should happen to push notification languages that are defined but the `manager_config` no longer includes that language, should they be deleted?

Its meant as a manager UI thing indeed. With that option in the manager_config, you make it available in the dialog on the When-Then rules. Technically this translates it to the proper JSON rule to send the notifications. So it has no impact on the backend in that sense. The JSON is still interpreted based on the languages set in there, whether that is done through the Manager UI app or in some other way.

If a language is removed from the manager_config, the text should remain in the rule. We could add an alert icon in the notification dialog of the When-Then when we find languages in the JSON that are currently not enabled in the UI?

**Comment by richturner** [comment]
This would be implemented in the notification message and the notification handlers will need to understand it and deal with language preference lookup.

**Comment by richturner** [comment]
User language updatedon the backend:

* Move language preference to a different key in local storage
* If old key exists send that lanuage to the backedn and store in new key
* Otherwise take device/OS default language

**Comment by MartinaeyNL** [comment]
As mentioned in the linked pull request, it's now up for review on the test1 deployment.
See PR #1436 for more details on the progress.
