### ISSUE TITLE
Alarms translations not visible

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#1404]
Translations not shown for alarms and alarm page. Seems a caching problem.

![Image](https://github.com/user-attachments/assets/6171670d-4ef3-4620-b014-08613bf40271)

**Comment by wborn** [comment]
Looks like all .json files are currently configured to be cached for 1800 seconds (30 minutes):

https://github.com/openremote/openremote/blob/d0167dbfcbd8391afc11e09b2e2258bdc8593a74/manager/src/main/java/org/openremote/manager/web/ManagerFileServlet.java#L60-L73

Request in the browser:

![Screenshot from 2024-09-12 16-37-17](https://github.com/user-attachments/assets/ef713e6d-e0de-478e-a233-9cc459250edc)
