### ISSUE TITLE
Gateway asset: can not delete a previously connected gateway asset

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1406]
Reproduce:
1. Create gateway asset
2. Set up manager interconnect on another realm/instance (from another realm within the same instance, might not matter)
3. Set the gateway asset to disabled
4. Delete the gateway (and all child assets)
5. Get error that it can delete the asset

Expected:
5. Gateway and all children are deleted.

Please read findings below.

**Comment by DonWillems** [comment]
Bonus bug:
1. Created gateway + interconnect from different realm
2. Delete gateway asset (while enabled)
3. See 400 error in console on the DELETE, but assets are still deleted
4. On the Interconnect page of the other realm, the status still shows 'CONNECTED'. This while the gateway asset was deleted.

Expected:
4. Manager Interconnect shows the status 'DISCONNECTED', since the gateway asset was deleted.

**Comment by DonWillems** [comment]
When using the demo setup I am only able to delete the gateway if all assets but the following are removed from smart city (manager interconnect from smartcity to manufacturer).
Could not find any relation to agents/depth of tree/group asset type..

![Image](https://github.com/user-attachments/assets/801ec7d7-8497-45c6-a114-d2e1f2d6c748)

After another try, it only worked then these assets remained:
![Image](https://github.com/user-attachments/assets/d11a2b94-1370-4e75-9221-4e2116a6db0c)

Can't really find the logic.
When linking the other way, deleting the gateway with the manufacturer assets gave no problem. It does not seem to be the length of the request/number of assets.

**Comment by wborn** [comment]
I can reproduce the issue.

It returns `false` [here](https://github.com/openremote/openremote/blob/181b51176e284dd326fdbb963a8975c2896d8bc7/manager/src/main/java/org/openremote/manager/asset/AssetStorageService.java#L888) which causes the error. It looks like it first removes gateways and their assets. Afterwards it tries to remove the remaining assets and can no longer find the gateway of assets that already got removed.

**Comment by wborn** [comment]
I tested if https://github.com/openremote/openremote/pull/1432 fixes this issue locally.
However it still shows the error when you delete a gateway with those changes.

**Comment by wborn** [comment]
I can no longer reproduce this issue with the latest changes in #1432. :+1:
