### ISSUE TITLE
Chart: charts in attribute history and KPI widget should show loading and timed out state

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1410]
The improvements made to the chart in the chart widget on the Insights page should also be applied to the chart in the KPI widget, and the chart in the history panel of the Assets page.

- Show loading state
- Show 'Data request timed out'
- Enable switching timeframe during loading/timed out (so cancel previous request)

**Comment by MartinaeyNL** [comment]
This has become a hanging issue / PR haha

Me and @DonWillems noticed a bug on Friday, which I'll pick up today.
I've moved the issue back to "In progress"
