### ISSUE TITLE
Unable to access OpenRemote via custom hostname and port

### ISSUE THREAD

**Issue by Eyuel-Military-Project** [openremote/openremote#1442]
[docker-compose - Copy.txt](https://github.com/user-attachments/files/17356690/docker-compose.-.Copy.txt)
Hi, 
I might be missing simple detail, but follwoing the quick start guid is not helping either.
Description: I am trying to access OpenRemote via a custom IP and port (e.g., 192.168.2.48:8443), but I can only access the system via localhost:8443. Here are the details:

What I am trying to do: follow the quick start guide and change the hostname and port to access OpenRemote from other devices on my network using the local IP (192.168.2.48) instead of localhost.
Observed behavior: I can access OpenRemote using https://localhost:8443, but when I try to access it using https://192.168.2.48:8443, it does not work.
Expected behavior: I should be able to access OpenRemote via the local IP (192.168.2.48) on the same machine and other devices on the network.

Docker Compose Configuration: copy of my docker-compose.yml is attached.

System Info:
OS: ubuntu 
OpenRemote Version: latest
Could you please help identify why this issue occurs when using a custom hostname?
Thanks and kind regards

**Comment by pierrekil** [comment]
Please post these type of questions on our forum https://forum.openremote.io/
