### ISSUE TITLE
Rules: When-Then: Add 'duration' to a condition on the LHS, to trigger the RHS if it has been true for the set time

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1448]
As a user I want to create a condition that has to be true for x minutes, so that the action is not triggered immediately.

e.g.
As a user I want to specify that the connection status of a device has to be false for more than 10 minutes before sending a notifications, so that it does not send notifications for each brief internet disruption of a device.

The duration can be added to every condition.

- Add duration mechanic in the JSON rules to track how long a condition is true
- Add controls to When-Then UI so that the user can set it.
   - The duration button appears together with the value field. If it is pressed, the duration field appears
   - The duration can be set in minutes (positive values only. Do we need an upper limit?)
   - if left empty, no duration is saved. If you would open the rule later, the duration field will not be shown anymore. The user can press the button again to open the field.
   - The 'not updated for' operator will force this field, see issue #1449 

![Image](https://github.com/user-attachments/assets/2988d2c6-c62f-47ed-9942-f4a6d3a5a660)

**Comment by richturner** [comment]
There is `RuleCondition.duration` in the model and implemented in the backend but this is an alternative LHS trigger to `RuleCondirion.assets`, this `RuleCondition.duration` is not used in the UI at all and is not utilised in the code base anywhere so this can be repurposed.

To implement this functionality look to enhance the `JsonRulesBuilder.assetPredicate` here:

https://github.com/openremote/openremote/blob/ca7aa7e517d53493726d5b153cc5bbdac012fda1/manager/src/main/java/org/openremote/manager/rules/JsonRulesBuilder.java#L197

Create a wrapper around the existing predicate that also stores and applies any time related state.

**Comment by dominiquekleeven** [comment]
Had a talk with Rich regarding the existing duration property.

The duration property needs to be changed in RuleCondition to a map, allowing us to associate an attribute with a specific duration, since we can have multiple attributes with a duration as part of a condition and these located on a different level
