### ISSUE TITLE
Improve AssetResource writeAttributeValue/writeAttributeValues endpoints to allow timestamp to be supplied

### ISSUE THREAD

**Issue by richturner** [openremote/openremote#1455]
The HTTP endpoints for writing attribute values don't currently allow a timestamp to be supplied, make the following change(s):

```
@Path("{assetId}/attribute/{attributeName}/{param1 : (\\d+)?}")
Response writeAttributeValue(@BeanParam RequestParams requestParams, @PathParam("assetId") String assetId, @PathParam("attributeName") String attributeName, Object value);
```

```
AttributeWriteResult[] writeAttributeValues(@BeanParam RequestParams requestParams, AttributeStateWithTimestamp[] attributeStates);

AttributeStateWithTimestamp extends AttributeState {
  protected Long timestamp;
}
```

**Comment by pankalog** [comment]
I dealt with this during my fleet integration as I had the same issue but from the MQTT side. Should I worry about having datapoints with newer timestamps at the time of insertion? Should I return a 500 in case of that?

**Comment by richturner** [comment]
The backend now deals with outdated data points so you don't need to do anything
