### ISSUE TITLE
Manager interconnect: gateway status does not update when gateway is deleted

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#1466]
**Reproduce:**
1. Create gateway + interconnect from different realm
2. Delete gateway asset (while enabled)
3. See 400 error in console on the DELETE, but assets are still deleted (this should be fixed)
4. On the Interconnect page of the other realm, the status still shows 'CONNECTED'. This while the gateway asset was deleted.

**Expected:**
4. Manager Interconnect shows the status 'DISCONNECTED', since the gateway asset was deleted.

**Note**
Possibly related to GatewayService.deleteGateway() not closing the existing websocket session

**Comment by richturner** [comment]
I just tried to recreate this issue on staging and I cannot @DonWillems can you confirm if this is still an issue as it seems to be resolved with the recent updates to gateway handling
