### ISSUE TITLE
Appearance page: update the manager_config.json cache after upload

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#1472]
Currently, when making changes on the Appearance page, and pressing the SAVE button,
you're manually required to do a force refresh of your browser window (CTRL+F5). This clears the
`manager_config.json` file in the cache, and will redownload the new version.

For users, this is really annoying, as they are not aware of this issue.
The best solution is to redownload the `manager_config.json` file, and overwrite the cache.
Alternatively, as a short-term solution, you can show a warning that users should reopen their browser.

**Comment by richturner** [comment]
The update endpoint returns the updated config, this should be loaded into the UI on successful save but something must be going wrong there.

**Comment by pankalog** [comment]
will be added to #1414 , but @richturner we'll probably need to use `fetch` to force-clear the cache, and then do a `window.location.reload()`. Any other ideas?

**Comment by pankalog** [comment]
Fixed by https://github.com/openremote/openremote/commit/9450339cdfa5cc785d58a0ad8a44e6564982633c
