### ISSUE TITLE
or-input: improve text field, add types

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#149]
- [x] Confirmation button + feedback/forward
- [x] Time of last update of value
- [ ] Design to vary based on attribute type, eg: 
- - [x] toggle = boolean 
- - [x] slider = percentage or range input
- - [x] input = text or number
- - [x] input multiline = json or multiline text?
- - [x] dropdown = enum
- - [x] dropdown multiselect
- - [ ] color picker = color
- - [x] button = event

DateTimePicker
Can not set hours in dropdown. Pressing 9, changes it to 8. Should be able to set a time and then confirm the input.

**Comment by richturner** [comment]
@DonWillems please extract remaining items to their own issues so we can close this
