### ISSUE TITLE
Create (and edit) agent

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#156]
- [x] dropdown '+' for 'Agent' in asset list
- [x] modal for agent with list to select protocol (see designs)
- [x] also reached when selecting edit mode 
- [x] Replicate all GWT agent asset / edit mode functionality
- - [x] Ability to change parent asset
- - [x] Ability to change location
- - [x] Ability to add/remove/modify(name) attributes
- - [x] Ability to add/remove/modify meta/configuration items

**Agent:** 
- 1, Set up connection
- 2, define call(s)
- 3, define payload parsing to attributes (as template?)

How to handle connection agent 'real assets'?

Protocols to be added in order importance:
- [ ] (Generic) HTTP????
- [ ] Edge Gateway???
- [ ] (Generic) MQTT???
- [ ] (Generic) TCP/IP???
- [ ] (Generic) UDP???
- [ ] KNX
- [ ] Velbus
- [ ] Z-wave
- [ ] Artnet DMX
- [ ] Tradfri

**Comment by DonWillems** [comment]
Proposal for edit agent page:

I've split up the different action associated with an agent. Connecting, collecting data and setting up the attributes. In case of auto-discovery protocols the panels should be changed.
Used the Strijp-S sorama api client and microphones as example for now. See edit asset issue for related mock-up.

![Manager Edit agent asset-02](https://user-images.githubusercontent.com/14177035/78509784-ea698000-7790-11ea-8798-0a7cad1445b1.png)

Clicking the add configuration item will bring up a menu similar to adding a rules item on the rules page. The menu list should only show items relevant for this agent type. Clicking it will add the correct input.
Items in the data table can be deleted/copied and moved in order.
