### ISSUE TITLE
Update icon font

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#160]
The icon font we use regularly gets updated with new icons.

- [x] (Automatically) update icon font.
- [x] Update references to icons that might be broken now since their update to v5

**Comment by richturner** [comment]
see `core/mdi-iconset-generator.js` which processes the `@mdi/svg` icons into a suitable format, the version spec for `@mdi/svg` in `package.json` should allow the latest version to be pulled but probably need a `yarn update` command in the `gradle build`.

**Comment by richturner** [comment]
On a separate note, the generated iconset is getting a little large so we might want a way of limiting to a subset of icons
