### ISSUE TITLE
Missing @RolesAllowed({Constants.READ_RULES_ROLE}) on RulesResource

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#163]
https://github.com/openremote/openremote/blob/f0b3f18bfc38a457d271f1e38bebc76b225b5c65/model/src/main/java/org/openremote/model/rules/RulesResource.java#L91

https://github.com/openremote/openremote/blob/f0b3f18bfc38a457d271f1e38bebc76b225b5c65/model/src/main/java/org/openremote/model/rules/RulesResource.java#L103

I'm 90% sure that there should be role restriction.

**Comment by richturner** [comment]
Tenant and asset rulesets now have a public read flag; role checks are now handled in the implementation to facilitate public read using the same endpoints.
