### ISSUE TITLE
Attribute card improvements

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#168]
- [x] Config sets default asset attribute, if not set, card empty
- [x] Top right asset attribute button for modal (same as chart). If title is too long, shorten with ellipses.
- [x] Select new attribute, overwrite previous
- [x] Local storage for chosen asset attribute (Check with Robin, multiple charts, arrange panels)
- [x] When card is empty (no config or asset id not found), show "+ set attribute" in middle of card
- [x] insights page has 1 chart, 4 attribute cards
- [x] insights page alignment of chart with attribute cards
- [x] Rearrange attribute card panel
- [x] Add start and end date/time of graph
- [x] Change graph color based on positive (green)/negative (red)/same (grey)
- [x] Smooths rounded graph joints
- [x] Add tooltip to graph that only shows the value where you hover
- [x] Make 'Add attribute' modal visually identical to add attribute modal of or-chart
- [x] Nice to have: abbreviate number when too big (to 1000k for 1000000 for example)

**Comment by vlichtenberg** [comment]
![image](https://user-images.githubusercontent.com/1921657/81547944-d7902f80-937c-11ea-91cf-72ef1fc1fcd6.png)
