### ISSUE TITLE
Rules page: add editors and status

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#182]
- [ ] Show status of rules engine, click directs to pre-filtered logs page
- [x] Groovy rules viewer/editor
- [ ] JS rules viewer/editor
- [ ] All 4 rules options under '+' for master realm, login as 'admin'
- [x] Show rule type behind name similar to how FLOW is shown

**Comment by pierrekil** [comment]
JS not added as 4th option
Remaining covered by #569
