### ISSUE TITLE
Asset tree: improvements/fixes

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#184]
- [x] Default sort by name
- [ ] Copy asset option
- [x] Synchronise on assets change in backend

**Comment by richturner** [comment]
Any sort other than name should have a secondary sort by name (e.g. by type then by name)

**Comment by richturner** [comment]
Asset tree should monitor asset changes and refresh accordingly, subscribing to asset events and refreshing tree should be sufficient

**Comment by pierrekil** [comment]
Replaced by #35
