### ISSUE TITLE
Issues Keycloak Demo

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#192]
- [x] Login page for 'smartcity' not styled
- [x] Account page for 'smartcity' not styled
- [x] Forgot password flow not styled
- [x] Account settings page disable for online demo

Not time critical, release July:
- [x] Remove shadow line around page
- [ ] Add translations
![Screenshot 2020-07-07 at 11 08 57](https://user-images.githubusercontent.com/11444149/86756110-6c906b80-c042-11ea-8a54-6899357b75a4.png)

**Comment by pierrekil** [comment]
- [ ] Remove shadow line around page
- [ ] Add translations
![Screenshot 2020-07-07 at 11 08 57](https://user-images.githubusercontent.com/11444149/86756189-7fa33b80-c042-11ea-8bc3-99f104ea0653.png)

**Comment by richturner** [comment]
I've made the keycloak `account` client roles configurable in our provisioning code and removed the `manage-account` role from the following users during provisioning:

- `testuser1`
- `testuser2`
- `testuser3`
- `smartcity`
- `building`

I have then marked the `Account` header menu item as requiring this role so in the demo environment only `admin` will be able to view the account page.

**Comment by richturner** [comment]
@pierrekil Can you please make a separate issue for keycloak translations as this is a separate piece of work, then this issue can be closed

**Comment by pierrekil** [comment]
I will
