### ISSUE TITLE
Change map

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#199]
Rotterdam area: https://openmaptiles.com/downloads/dataset/osm/europe/netherlands/rotterdam/#8.97/51.9021/4.3567

**Comment by richturner** [comment]
I can replace the default mbtiles file with this one but all our demo assets are set to Eindhoven location and we won't have map tiles for this location

**Comment by pierrekil** [comment]
Go ahead. No problem, we will move the manually in 'demo' and Don will pick up actual assets and attribute structure in Demo.

We only need to plan to put them back in provisioning code.

**Comment by aktur** [comment]
It would be good to have a CLI for tasks like this. With it we could skip the compiled provisioning code all together. Safer and faster - no credentials in the source, which is a bad idea anyway.

**Comment by richturner** [comment]
Updated mapdata but mapsettings will also need adjusting along with demo assets
