### ISSUE TITLE
Handle connectivity errors

### ISSUE THREAD

**Issue by ebariaux** [openremote/openremote#21]
- [x] Handle errors of main web view loading (initial URL) by displaying native error message instead of letting the web view display the error.

- [x] The native error messages should be either fatal (the app should exit clean when user clicks "OK" button in an error dialog) or non-fatal (user can continue using the app with some weird behaviour such as buttons not working, after a short-lived toast with the error message was shown).

- [x] Handle device notifications for connectivity and display an error screen overlay when no connectivity is detected.

- [x] Implement error/status bridge between WebView and shell. The loading and any error status should be send from WebView to shell and displayed in whatever makes most sense.

- [x] If the WebView makes a server (HTTP call or WebSocket connection) request with an invalid access token, this should be handled gracefully by redirecting to login page.

- [x] Also fix #35

**Comment by mickz18** [comment]
Define list of problems -> define expect result
test those problems
