### ISSUE TITLE
Add rules to setup code

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#218]
- [x] Add rules currently on demo.openremote.io to the setup code.
- [ ] Make use of percentage in WhenThen rules possible. Then add the rule 'When ParkingGroup:totalOccupancy > 90, Then send an e-mail'
- [ ] When saving a WhenThen rule with '0' as a value, '0' is not shown anymore.
- [x] page-rules default config should not exclude AssetType.BUILDING.type!,
- [x] Add RULE_STATE to the totalPower attribute of consumption and solar assets
- [x] Add location as attribute to the Console assettype, so that it can be selected in When Then rules when using 'Any of this type'
- [x] Add RULE_STATE and STORE_DATA_POINTS to attributes of the weather asset: humidity, temperature, wind direction, wind speed.

**Comment by richturner** [comment]
@DonWillems please move remaining two items to JSON bug issue
