### ISSUE TITLE
Have customisation mechanism for project specific consoles

### ISSUE THREAD

**Issue by ebariaux** [openremote/openremote#22]
Have a way to customize certain aspects of the console for a specific project and build that.
It should be possible to have custom
- icon
- package name
- specific parameters

**Comment by mickz18** [comment]
Have change build variant for dev staging production with different app name and ID so it can be install simultaneously one device

**Comment by pierrekil** [comment]
Consoles in place. Standard app with project/realm specification and option to make custom app.
Docs will be part of 'custom project', see #566
