### ISSUE TITLE
Better option for view / edit mode?

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#256]
- [x] Both modes to allow deleting/duplicating/adding/ (based on rights)
- [x] Move the 'edit/view' mode as toggle to asset page (on the right)
- [x] + Asset - Modal extension: to show option to set parent and name (see screenshot)
- [x] Config option for + Asset - Modal, to enable which asset you can add the specific asset type.

![Screenshot 2020-09-21 at 10 58 42](https://user-images.githubusercontent.com/11444149/93749016-79603c80-fbf9-11ea-8592-e7b2a42d0a83.png)

**Comment by richturner** [comment]
Not sure about the big textual button but could make it possible to delete, copy/add without being in edit mode

**Comment by pierrekil** [comment]
Maybe the button just with the current icons? Anyhow good to have functions in both modes

**Comment by pierrekil** [comment]
Is it possible to add the delete, add buttons without being in edit mode on short notice? Next, Robin can pick it up on Monday and add 'duplication' and move the view/edit button out of the first bar (for now: maybe just the same way as we do rules: the Toggle 'Realm' versus 'Global')

**Comment by pierrekil** [comment]
Still to add 'name' in modal and make 'duplicate' work.
