### ISSUE TITLE
User and role management page improvements

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#273]
- [x] Realm selection is not persistent when refreshing which can cause confusion/mistakes
- [x] Menu, roles icon: account-box-multiple
- [x] Mobile menu, space between icon and text
- [x] Responsiveness for both pages: on mobile size, single column of input fields.

**User management**
- [x] Update  page/content when realm is changed by a super user.
- [x] Don't show item in the menu when you don't the permission to read or write them.
- [x] Make entire row clickable to open the item
- [x] Allow to set role direct when adding a new user
- [x]  Enabled default on true
- [x]  Responsiveness improve
- [x] Add 'Add new user' button at bottom of the list (and top right?)
- [x] The table should be within a panel, now the table is the panel. See asset edit mode.
- [x] Styling updates
- [x] When adding user, dropdown-panel should be default opened (now an extra action to open) and have a cancel button to cancel the action (or the delete already in place if that fits the system better).
- [x] Adding user the first time and first time saving, opens the last user in stead of the newly added user
- [x] Deleting user should first ask confirmation "Are you sure you want to delete this user?"
- [x] Translations of user fields, table headers, menu options (top right)
- [x] Hide buttons (create, update, delete) if no write access
- [x] Selected role not saved on create. Only after setting a role on an existing user. And then a refresh is needed before you see it.
- [x] Same for other changes to existing user. Only visible in list after refresh.
- [x] Firstname, Lastname and e-mail have * when creating a user (not in the fields of existing user). Should be removed.
- [ ] Check whether passwords are identical when resetPassword and repeatPassword, turn 2nd into RED characters and refuse to save or create
- [x] Translate firstName lastName resetPassword repeatPassword
- [x] Users shouldn't be able to change their own role (potentially locking themselves out). Make field disabled
- [x] Use same width and exact title placement as Insights page (also check alignment of icon with title text). Same for Roles.
- [x] update margins, see new image:
![image](https://user-images.githubusercontent.com/14177035/105676637-181fe100-5eeb-11eb-955f-a522dd442d1c.png)

**Role management**
- [x] Styling updates
- [x] When adding composite role, dropdown-panel should be default opened (now an extra action to open)
- [x] No save button for composite role, only looks saved when adding another role, but it is not saved
- [x] Add input field for description of the composite role
- [x] Deleting role should first ask confirmation "Are you sure you want to delete this role?"
- [x] Change "Role" in table header to "permissions"
- [x] Separate permissions in 2 columns read and write. Columns have headers "Read" and "Write". Columns are sorted a-z. Show role name (without read: or write:) + ": " + role description. If a role does not have read: or write:, then create a column "Others" with those roles.
- [x] Responsive: on mobile size, text wrap the permissions.
- [x] When a new composite role is added without any permissions it's shown as a regular role in the list. Prevent users of creating a composite role without selecting any roles
- [x] Title should be Roles with the correct icon
- [x] Same margin update as Users.
- [x] Make page responsive: text wrap for roles, size dropdown accordingly

![Screenshot 2021-01-18 091730](https://user-images.githubusercontent.com/14177035/104890276-a6d2b200-596f-11eb-9c9f-224f4a7821fa.png)
![Screenshot 2021-01-18 092856](https://user-images.githubusercontent.com/14177035/104890279-a76b4880-596f-11eb-84aa-2c15948944ad.png)

**Comment by robin-dekkers** [comment]
- [ ] Hide buttons (create, update, delete) if no write access
- [ ] Selected role not visible after creating user, is shown after refresh

**Comment by pierrekil** [comment]
**User management**
- [ ] Check whether passwords are identical when resetPassword and repeatPassword, turn 2nd into RED characters and refuse to save or create
- [ ] Refresh should open same realm, now goes back to 'Master'

**Role management**
- [ ] Friendly names for roles in language file

**Comment by pierrekil** [comment]
added #279 for last item
