### ISSUE TITLE
Review security architecture

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#32]
- [ ] HTTP XSRF protection either through CORS or if that's still a problem, through double-submit of form hash in header (cookie) and body (json field), does auth-token help?

- [ ] WebSocket XSRF protection (see https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html) must be enabled on WebsocketComponent with Jetty CrossOriginFilter etc.

- [ ] Consider "Unlimited Strength Jurisdiction Policy" package for the JVM and if/how we need those algorithms

- [ ] Java Problems: http://web-in-security.blogspot.ca/2015/09/practical-invalid-curve-attacks.html

- [ ] Manager servlets should include CORS headers when in dev mode to allow console development from different host (e.g. node based HTTP server with live reload)

- [ ] Fix CORS filter used in Resteasy deployment (see below comment)

**Comment by richturner** [comment]
Current custom CORS filter used in resteasy deployment doesn't support pre-flight OPTIONS request; should migrate to the standard Resteasy CORS filter.
