### ISSUE TITLE
Set up Github repository with the customer project filestructure

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#333]
Set up private repo where the files will be stored

**Comment by aktur** [comment]
Created as https://github.com/openremote/customer-project-filestructure

**Comment by aktur** [comment]
@DonWillems How do you want to work with it? A subdirectory per customer or branch per customer? IMHO, this can work up to 100 clients. For larger number we would need to revisit and probably port it to a different solution.

**Comment by DonWillems** [comment]
A subdirectory per customer seems most clear/organized to me. I don't know what the downsides are, if any?

**Comment by aktur** [comment]
Yes, the only downside is that it does not scale. With 100+ clients would be very hard just to scroll through it. Anyway, I close this issue for now and use this repo a further for setting clients.
