### ISSUE TITLE
Is e-mail server not set for staging.demo?

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#343]
Wanted to test 'forgot password flow'

**Comment by richturner** [comment]
I don't know where the `docker-compose` profiles for the demo deployment are located so don't know what environment variables are being set (something to discuss in weds call); I know in the past we didn't set credentials as it could be open to abuse.

**Comment by aktur** [comment]
staging.demo uses swarm/swarm-docker-compose.yml
demo uses profile/demo-openremote.yml

In both mail server isn't set.
