### ISSUE TITLE
Adding weather through HTTP Agent not (always) working

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#359]
- [ ] first create a new realm
- [ ] when adding the openweathermap API, adding the URI set's the Agent to 'Connected', but when adding 'Request query parameters' (with correct key), the Agent goes into error mode. Disabling and enabling get's it connected again.
- [ ] the connection status should be read only without the ability to open up the dropdown.

**Comment by richturner** [comment]
Fixed by 541f5760cb51c7ee0085dde86c20dcb8d50be181
