### ISSUE TITLE
Consoles needs update

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#362]
Consoles still use /main which should be replaced by /manager:

![IMG_1315](https://user-images.githubusercontent.com/11444149/110011241-7c6e6580-7d1f-11eb-9742-ed225b081b87.png)

**Comment by pierrekil** [comment]
It got a bit further, still showing error message, but Keycloak in background. When pressing 'OK' you can still login.
![IMG_1317](https://user-images.githubusercontent.com/11444149/110252297-023f1a80-7f85-11eb-8edf-d819237053f2.png)

**Comment by Miggets7** [comment]
After some investigation, it seems demo production needs updating

**Comment by richturner** [comment]
If @pierrekil is putting `staging.demo` into the app, why is `demo` involved at all? Or am I missing something here?

**Comment by Miggets7** [comment]
Because the config of staging is the same as production and points to production. The AppConsoleConfig json file point to production. So production should at least be running with latest code which can show the console_loader UI

**Comment by richturner** [comment]
Still don't understand why it points to production, staging and production are independent and should not depend on each other, if this was done to simplify setup then that should be rectified. If it's for some other reason then we need to re-evaluate this.
