### ISSUE TITLE
Assets: Agent configuration import and discovery

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#384]
As a user I want to discover or import assets that are connected to my local system that has that functionality so that the connected assets are automatically added to the OpenRemote system.

This covers the following two use cases:
- As a user I want to upload a file with my KNX or Velbus configuration to an agent, so that the assets configured in there are added to the OpenRemote system.
- As a user I want to discover the devices connected to my Z-wave controller, so that they are created in the OpenRemote system.

Design of the file selector:
https://docs.google.com/document/d/1LZOKCIng-_mssSwULkTBFgeaR5Okjo6I1gM3VEAqHvE/edit#heading=h.dpe5t3tyxdg

Discovery is a push button. Create attribute-input of button that uses the attributename as text.

Tech (placeholder, needs review):
- Check asset properties whether it has discovery or file import (review comment), then add discovery button or import file field at top of attributes in panel

**Comment by richturner** [comment]
'AgentDescriptor` contains info about whether a particular `Agent` type supports `assetImport` (import from a protocol specific file - `Velbus`=`*.vlp`, `KNX`=`*.knxproj`) and/or `assetDiscovery` (the agent instance searches for devices connected - `ZWave` is the only protocol that supports this at present).

For `AgentDescriptor` (see `model/src/index.ts` - make sure npm run modelBuild has been run to generate this from the `java` model):

```
export interface AgentDescriptor extends AssetDescriptor {
    descriptorType: "agent";
    name?: string;
    icon?: string;
    colour?: string;
    instanceDiscoveryProvider?: boolean;
    assetDiscovery?: boolean;
    assetImport?: boolean;
}
```

REST endpoint for doing discovery/import is [AgentResource](https://github.com/openremote/openremote/blob/master/model/src/main/java/org/openremote/model/asset/agent/AgentResource.java#L73).

For import you need to post a `FileInfo` `JSON Object` which can contain either text or binary (i.e. base64 encode the file content), this mechanism needs to be improved as this is not very efficient but works for now. The requests will run for however long the import/discovery takes so the browser should show a busy indicator and not allow additional imports/discovery requests whilst the previous is running.

There are tests in the system that test the `velbus` and `KNX` import and you can use these project files for manually testing the import functionality also, they can be found in:

https://github.com/openremote/openremote/tree/master/test/src/main/resources/org/openremote/test/protocol

**Comment by vlichtenberg** [comment]
Hi @richturner, came to the point where I started interacting with the rest service for Zwave discovery, but the backend told me `Agent protocol is disabled or is being deleted`. The agent I've added is not disabled, and as far as I know also not being deleted. I found that in the Java code, there's a check going `protocol == null` which triggers it, but I'm not sure how to deal with this myself. 

I'll proceed with the file upload for Velbus and KNX now.

**Comment by vlichtenberg** [comment]
Regarding importing files (at least KNX): I think I've constructed the object as expected by the API but it's throwing 405 method not allowed. Not sure why; it's not providing further logging on my side either.

It's all in my branch. I hope the hotlink to this compare screen works: https://github.com/openremote/openremote/compare/feature/setup-panel?expand=1#diff-8ea35222567827fca8d3b28b036e04ad459248f74b2ce0cef704cd4852284c25R388

**Comment by richturner** [comment]
> Hi @richturner, came to the point where I started interacting with the rest service for Zwave discovery, but the backend told me `Agent protocol is disabled or is being deleted`. The agent I've added is not disabled, and as far as I know also not being deleted. I found that in the Java code, there's a check going `protocol == null` which triggers it, but I'm not sure how to deal with this myself.
> 
> I'll proceed with the file upload for Velbus and KNX now.

There's no tests that cover `zwave` discovery and don't think it's been manually tested since before I did a big refactor, must have introduced a bug in there somewhere....will take a look.

**Comment by richturner** [comment]
I've taken a look and the point in the code you are referring to is a valid check, I've improved the error message as there can be another reason why the protocol is null and that is because the `agent` is misconfigured and therefore the protocol cannot be started. Likely because you don't actually have any `zwave` hardware (`usb` stick) or the `agent` attributes haven't been set correctly to connect to it.

**Comment by DonWillems** [comment]
I have a zwave stick and door sensor here at my desk. If I understand correctly I should be able to check out Vincents branch and try the discovery?

**Comment by rainerhitz** [comment]
I'm currently working on this issue. I've seen that at least the zwave-data: volume is missing in the docker-compose.yml file. The devices: mapping is also missing.

**Comment by rainerhitz** [comment]
After adding the missing zwave-data: volume and devices: mapping in the docker-compose.yml file I've seen an IllegalStateException in the log caused by the following line in the doStart() method of the ZWaveProtocol implementation.

String serialPort = agent.getSerialPort().orElseThrow(() -> new IllegalStateException("Invalid serial port property"));

It seems that the serial port configuration is missing.

**Comment by richturner** [comment]
Indeed if that `attribute` is not set then it doesn't make sense for the `protocol` to continue, the add `agent` UI doesn't currently provide a way for supplying required `attribute` values so these need to be set after the add `agent` dialog and the backend will re-initialise the protocol and it should succeed this time.

**Comment by richturner** [comment]
> I'm currently working on this issue. I've seen that at least the zwave-data: volume is missing in the docker-compose.yml file. The devices: mapping is also missing.

Didn't see a need for another data volume, any persistent data should be stored in `/deployment` dir which is then volume mapped to the `deployment` named volume.
