### ISSUE TITLE
Asset: History timescale not behaving correctly

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#390]
- [x] History view scales incorrect for different timewindows
- [x] Dropdown field to narrow to read label name
- [x] Insights charts and attribute card display the same incorrect behaviour for the timescale

**Comment by richturner** [comment]
Just noticed another issue with moving the time window in attribute history view, it's not moving by the correct amount, I will look at this in the morning.

**Comment by richturner** [comment]
Time window issue is now fixed as well
