### ISSUE TITLE
Rules: Asset type select behaviour and Rules schedule dialog

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#392]
- [x] Asset type selection in when then rules do not show the colour of the asset type anymore
- [x] Translations missing in Rules schedule dialog
- [x] Pointer cursor not shown for day selection control in recurring rule

**Comment by richturner** [comment]
@DonWillems `apply` is missing from the translation files (at least from Dutch), can you add please.

**Comment by richturner** [comment]
Can't reproduce asset type picker issue seen on `staging.demo`, maybe I've fixed this unknowingly, if it is still there on redeploy I'll investigate more

**Comment by DonWillems** [comment]
Added Dutch translations, quite a few were missing for that modal.
