### ISSUE TITLE
Openremote docker on windows not working.

### ISSUE THREAD

**Issue by gicohdawer** [openremote/openremote#402]
I have installed the openremote on docker desktop and tried to access it over localhost. however the browser says: HTTP ERROR 403. and does not open any kind of page. The docker log and docker compose is also attached with the issue. my docker desktop version is: v20.10.5

Need help.

[Log & Docker files.zip](https://github.com/openremote/openremote/files/6316036/Log.Docker.files.zip)

**Comment by aktur** [comment]
Can you run the UI test and send paste results? If you have python3 installed to run the test please do:
> pip3 install -U openremote-cli
> or-test-http-rest --dnsname localhost --password secret -vv

In the last 12h there was a broken image pushed to the docker hub registry and there is a chance that you have it. If above test fails, then try to pull a new image
> docker pull openremote/manager
and run the test again.

**Comment by aktur** [comment]
If you don't have python installed you can run this test as:

> docker run --entrypoint or-test-http-rest openremote/openremote-cli --dnsname localhost --password secret -vv

**Comment by aktur** [comment]
By the way, a better place for this kind of questions is https://forum.openremote.io

**Comment by gicohdawer** [comment]
D:\Docker Containers\openremoteDemo>docker run --entrypoint or-test-http-rest openremote/openremote-cli --dnsname localhost --password secret -vv
INFO:root:Namespace(delay=1, dnsname='localhost', dry_run=False, no_quiet=False, no_quit=False, password='secret', realm='master', user='admin', verbose=2)
INFO:root:setting password for user 'admin' at 'localhost' in realm 'master'
INFO:root:/usr/local/lib/python3.8/site-packages/webbot/webbot.py:/usr/local/lib/python3.8/site-packages/webbot/drivers/chrome_linux
Config created in /root/.openremote/config.ini
0. Login into localhost
Traceback (most recent call last):
  File "/usr/local/bin/or-test-http-rest", line 8, in <module>
    sys.exit(manager_test_http_rest())
  File "/usr/local/lib/python3.8/site-packages/openremote_cli/scripts.py", line 745, in manager_test_http_rest
    driver = _manager_ui_login(url, user, realm='master')
  File "/usr/local/lib/python3.8/site-packages/openremote_cli/scripts.py", line 558, in _manager_ui_login
    driver.go_to(f'https://{url}/manager/?realm={realm}')
  File "/usr/local/lib/python3.8/site-packages/webbot/webbot.py", line 419, in go_to
    self.driver.get(url)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: headless chrome=90.0.4430.72)

**Comment by gicohdawer** [comment]
Here is the output of the above docker command. I was more comfortable with docker so used that.

*Pursuing the issue here to avoid unresolved copies.*

**Comment by aktur** [comment]
I'm sorry, but it seems that this test does not work from docker container, selenium chrome driver has problems communicating with chrome browser, therefore the only option to run this test is with Python. I need to investigate how to make it possible to run from inside docker, but it won't be this week.
