### ISSUE TITLE
Velbus - Master / Local alarm mode change 

### ISSUE THREAD

**Issue by MDAR** [openremote/openremote#41]
The command to set alarm time status from On to Off includes the parameter to select Master or Local group.

1:master:on
1:local:on

The on and off states are working, but the master / local mode is not changing.

(Bug currently seen in V2.x)

**Comment by richturner** [comment]
This is not something that is available as a standard command and requires writing directly to the memory of the device(s) and the location to write to varies from device to device and possibly even between firmware versions, unless this functionality is really useful we should probably avoid trying to do this.
