### ISSUE TITLE
Velbus - Press / Release / Long_Press not triggering actions within other Velbus modules

### ISSUE THREAD

**Issue by MDAR** [openremote/openremote#42]
In VelbusLink actions are set within modules to respond to Press / Release / Long_Press events from other modules.

for example, a relay channel can start or stop an interval timer when it sees a Press event from a module.

The concept for OpenRemote was that by mimicing a Press / Release / Long_Press event for a module (for example an input module) any actions programmed into other modules would respond.

For example.

A glass panel button will start and stop an interval timer to trigger the multi-step dimmer states in VMB4DC channels.
It should be possible for OpenRemote to mimic this button event. 

This doesn't appear to be happening in V2.x

**Comment by richturner** [comment]
Tested this in OR 3.0.

Linked OLED channel 1 button to VMB1RYNO channel 1 as On/Off.

If I mimic a PRESS on OLED channel 1 from OR 3.0 then the actuator turns on, when I then mimic the PRESS again the channel turns off.
