### ISSUE TITLE
Data export API

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#420]
As a user I want to export raw data of selected asset attributes for a specific time range as a .csv so that I can use it for further data analysis in other tools.

This should be possible using the data export page in the manager UI. For that to work the API needs to be extended.
It should be possible to extract all datapoints:
- [x] within the specified timeframe
- [x] of all selected asset attributes (multiple assets of which multiple attributes can be selected)
- [x] as a csv file (does one file, file per asset, or file per asset attribute make most sense?)

**Comment by pierrekil** [comment]
Data export should deliver CSV which splits attributes and values per column with header name = attribute name. First column is timestamp.
