### ISSUE TITLE
Users: add permissions to role select

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#429]
As an admin I want to select roles or individual permissions for a user, so that I can set more specific permissions for a user.

When a user is programmatically created, it can have one or more roles (permissions) instead of a composite role (role). This is not supported by the current UI. This will also solve that as permissions can be seen in the role list.

- [x] Make the role select multi-select
- [x] Add two headers in the list: Roles and Permissions
- [x] When a composite role is selected, show it's permissions as disabled selected in the list (so that the user know which will be set)
- [x] When a permission is selected, and then a composite role is selected including that permissions, set only the composite role and not the permission (so that it won't be set twice).
- [x] Multiple composite roles can be selected even if they have overlapping permissions
- [x] A composite role can include another composite role, make sure the 'disabled and selected' behaviour is also applied here
- [x] Show the selected roles and permissions in the input field.

https://docs.google.com/document/d/1LZOKCIng-_mssSwULkTBFgeaR5Okjo6I1gM3VEAqHvE/edit#heading=h.3v8nbuq3nfpv

**Comment by pierrekil** [comment]
'Add user' function (creating a new user) is broken

**Comment by richturner** [comment]
I reverted the broken code and a user confirmed it was working now. What exactly is still broken?

**Comment by pierrekil** [comment]
Sorry for confusion... It's Vincent work (separate branch) which still needs the fix.
