### ISSUE TITLE
KNX Attribute issues in rules

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#436]
When the KNX ETS test file is imported and the created assets are used in WHEN-THEN rules, the RHS selected asset always shows the attribute with same name as asset name and not the expected attributes with an operator
<img width="1571" alt="Screen Shot 2021-06-09 at 21 48 16" src="https://user-images.githubusercontent.com/11444149/121419984-e32d9b80-c96c-11eb-9830-de72a81ea513.png">

**Comment by richturner** [comment]
This indeed is a bug in the `when-then` rules specifically actions for `boolean` attributes, I have now pushed a fix for this
