### ISSUE TITLE
Secret not load

### ISSUE THREAD

**Issue by nachocr26** [openremote/openremote#441]
Hi, 

My problem is in User page. When I will create a new service user, the secret key not load (even when I click on regenerate secret, not load), and then, when I save the user, does not created. 

The manager version is latest.

**Comment by richturner** [comment]
Hi thanks for bringing this to our attention, seems like a change in the latest keycloak version `13.0.1` caused this, I've pushed a fix so please try pulling latest manager image (timestamp must be greater than this post time as image is still being built as I type).
