### ISSUE TITLE
Insights: Apply add-attribute-dialog to chart

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#443]
- [x] Apply add attribute dialog (used for data export) to chart
- [ ] #485

**Comment by pierrekil** [comment]
When attributes are selected for chart, browser needs a manual refresh before showing the updated chart data in the chart

**Comment by pierrekil** [comment]
Only the attributes which have a 'store data point' configuration item, turned on are shown in the attribute selector.
However, attributes which have an 'agent link' configuration item, also store the data points, despite the fact that is not shown explicitly as an additional 'configuration item'. These attributes should also be shown in the attribute selector.

**Comment by vlichtenberg** [comment]
Created a separate ticket (#485) for the open task because it's going to be quite a bit of work and I don't want it to block the other tasks in this ticket.
