### ISSUE TITLE
Attribute panel week/day identical

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#444]
Attribute panel: day and week view are identical
![Screenshot 2021-06-21 at 08 56 27](https://user-images.githubusercontent.com/11444149/122719636-c0ee2480-d26e-11eb-9fd2-b113d7b541f2.png)
![Screenshot 2021-06-21 at 08 56 34](https://user-images.githubusercontent.com/11444149/122719641-c21f5180-d26e-11eb-96dd-bbb84f7205f0.png)

**Comment by richturner** [comment]
Strangely I cannot reproduce this issue, no matter what I try it seems to work correctly.

**Comment by pierrekil** [comment]
When logging in on Staging demo, don't you see the issue?

**Comment by richturner** [comment]
Oh, yes it is reproducible on `staging.demo` but running the latest code locally and trying on `staging.iems` I cannot reproduce

**Comment by pierrekil** [comment]
Yes, also 'gone' on iEMS for me. Will close and watch :-)

**Comment by aktur** [comment]
staging.iems has 5 days old image. staging.demo image is 13 hours old.
