### ISSUE TITLE
Datetime pickers do not work on Firefox

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#445]
Sadly, firefox does not support datetime-local so the date time input fields in history, chart and data export are not usabled.

Firefox userbase is big enough (3rd, similar to Safari) to make sure this works.

Option is to make it date + time picker, or load a separate picker when on Firefox?

**Comment by richturner** [comment]
Quite a bit behind safari:

https://gs.statcounter.com/

**Comment by aktur** [comment]
However for openremote.io Firefox is more popular than Safari - 9.8% vs 7.3%

[statcounter screenshot](https://www.dropbox.com/s/k2h9p9j7y24z5ei/screenshot%202021-06-21%20at%2022.26.54.png?dl=0)

**Comment by aktur** [comment]
logging into demo.openremote.io shows that Firefox is a bit more popular than Safari in our target group:
```
└─[0] <git:(master 72a54766d✱✈) > or manager --list-public-assets -t --realm smartcity | grep name | grep Firefox | wc
      92     187    1953
└─[0] <git:(master 72a54766d✱✈) > or manager --list-public-assets -t --realm smartcity | grep name | grep Safari | wc 
      61     122    1220
└─[0] <git:(master 72a54766d✱✈) > or manager --list-public-assets -t --realm smartcity | grep name | grep Chrome | wc
     378     783    7749
└─[0] <git:(master 72a54766d✱✈) > or manager --list-public-assets -t --realm smartcity | grep name | wc              
     576    1220   12128
```

**Comment by richturner** [comment]
Haven't tracked down any timescales on an implementation of this on the Firefox timeline so we either need to avoid using this input type or roll our own component (dialog with separate date and time inputs)

**Comment by DonWillems** [comment]
Firefox did something, now its shows date time and it has a picker. Although time is not part of the picker yet, you can set it in the input element after selecting the date. So good enough I guess
