### ISSUE TITLE
Users and Roles: Add admin checkbox to users, remove 'read:admin' and 'write:admin'

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#448]
As an admin I want to give other users the permission to CRUD users, roles, and realms, so that they can also add new users.

As an admin user (superuser or realm admin) you will have access to the Users and Roles pages. An admin user of the Master realm will have access to Realms.

Users page:
- [ ] Add 'Admin' checkbox to the options per user on the Users page.
- On the Master realm, the user with admin check will become a Superuser (able to CRUD realms)
- On any other realm, the user will become realm admin.
- [ ] Disable role select and show 'All permissions' when admin is checked and give the user all roles (on save)

Roles page:
- [ ] Remove the roles 'read:admin' and 'write:admin' from the roles list.
- [ ] Check that the access to Users, Roles, and Realms is correctly restricted to the admin users.

https://docs.google.com/document/d/1LZOKCIng-_mssSwULkTBFgeaR5Okjo6I1gM3VEAqHvE/edit#heading=h.8px1kt3smeh5

**Comment by pierrekil** [comment]
added to #568
