### ISSUE TITLE
Data export: time range selects automatically change

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#450]
Replicate:
- On data export page add an attribute
- Time range selects will change its dates to the oldest datapoint available for the attribute.

Expected:
- On data export page add an attribute
- Time range select 'to' stays set as time of page load, and 'from' as time of page load minus one month.

**Comment by vlichtenberg** [comment]
Fixed in https://github.com/openremote/openremote/commit/2f9da0035f7c4d44bb810cc4d5654d3370f711d3
