### ISSUE TITLE
openremote/manager container issue

### ISSUE THREAD

**Issue by harsha9292** [openremote/openremote#452]
Unable to pull openremote/manager container from Docker. Trying to run the docker-compose.yml file on Ubuntu server but openremote/manager container installed with health : unhealthy
![openremote error](https://user-images.githubusercontent.com/66071201/124386694-3808cb80-dcf9-11eb-9809-098bbab95689.png)

**Comment by harsha9292** [comment]
> Unable to pull openremote/manager container from Docker. Trying to run the docker-compose.yml file on Ubuntu server but openremote/manager container installed with health : unhealthy
> ![openremote error](https://user-images.githubusercontent.com/66071201/124386694-3808cb80-dcf9-11eb-9809-098bbab95689.png)

**Comment by KloudCoder** [comment]
Same here. Any updates

**Comment by richturner** [comment]
Please provide the logs from the unhealthy container, cannot help without those.

Please use the forum for this discussion and an issue can be used when an actual problem is identified with our code.

https://forum.openremote.io/
