### ISSUE TITLE
Creating realms, users by CLI

### ISSUE THREAD

**Issue by dpaardenkooper** [openremote/openremote#458]
Dear support team Openremote,

Yesterday i created my own openremote environment on AWS confirm the github docker-compose file.
DNS and Cert are operational. I can log into the UI. But creating buttons aren't working.

Are the openremotecli commands I can run local on the docker host itself, for creating the users and MQTT user accounts? If so, can you share them?

On this link, they aren't documented or at least I couldn't find them.
https://github-wiki-see.page/m/openremote/openremote/wiki/User-Guide:-OpenRemote-CLI

Kind regards,
Dinant

**Comment by aktur** [comment]
openremote-cli does not support creating realms users yet. At this moment the further development of this tool is stale. It would be indeed a good extension. The tool is open source and ready for contributors. If you can help, be welcome.

**Comment by dpaardenkooper** [comment]
Thnx Aktur. That explains why it wasn't working. I will keep it in mind ;).

**Comment by dpaardenkooper** [comment]
Question answered. The function is not in the openremote-cli yet.
