### ISSUE TITLE
mqtt client data not coming in into openremote manager

### ISSUE THREAD

**Issue by dpaardenkooper** [openremote/openremote#459]
Dear all,

Creating mqtt connections to openremote.
Followed the tutorial: https://github.com/openremote/openremote/wiki/Tutorial%3A-Connect-your-MQTT-Client
Result:
-  Openremote is working. 
-  MQTT explorer can make connection. Can't retrieve information (channel / topics) or send data (not visible in openremote).

MQTT device  esp8266v3 to openremote.
-  It complains that bad username or password. We use the extension as described in the tutorial {realm}:{username}.

Please help.

**Comment by mmmherma** [comment]
Hi!

Following [this tutorial](https://github.com/openremote/openremote/wiki/Tutorial%3A-Connect-your-MQTT-Client#create-a-service-user) some errors occurs. The solution that worked to me was:

1. Add the desired `Linked asset` when create the client service, so steps will be like:
```
## Create a service user
The service user will give programmatic access to the MQTT client.
1. Go to the users page and create a new service user (second panel on the page)
2. Name the service user `mqttuser` and give the user the read and write role for the sake of convenience. It is advised to configure a more restricted role for your service users.
3. Link the desired asset(s) to the user.
4. Click 'Create', a secret will be generated automatically.
5. Open the 'mqttuser' user to see and copy the secret
```
2. Make sure mqtt [client id remains identical](https://forum.openremote.io/t/failed-to-subscribe-to-mqtt-topic/1219/5).

Do you know any way to PR directly to the wiki?

Thanks!

**Comment by richturner** [comment]
Thanks for the infor we'll look into it @DonWillems

**Comment by DonWillems** [comment]
Linking to assets is only needed when the service user has the realm role 'restricted user'. @mmmherma Did you set that on your service user? Maybe the wording of "It is advised to configure a more restricted role for your service users." is a bit confusing?

I added a line about keeping the clientID identical to the wiki page

**Comment by mmmherma** [comment]
Yes, you are right! No need to link assets if `restricted user` is not set :blush: 

Thank you very much @DonWillems
