### ISSUE TITLE
KNX Protocol Connection Status not updating

### ISSUE THREAD

**Issue by richturner** [openremote/openremote#46]
The KNX protocol doesn't react to disconnection events without something sending a command first so internal protocol state could be out of sync with actual KNX devices.

Seems that Calimero doesn't actively monitor the connection.

**Comment by mredeker** [comment]
Calimero should monitor. I am not sure which intervall is used where Calimero checks validity of connection. I will have to look into it. Did you unplug the network calble or how did you produce error?

**Comment by richturner** [comment]
I just unplugged the network cable from the IP interface; I quickly looked at the callbacks and none of them seem to fire but I haven't looked at the Calimero docs.

**Comment by richturner** [comment]
There is a heartbeat running but it only runs every 60s; after this time then the disconnect will be detected
