### ISSUE TITLE
Agent link JSON issues

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#467]
- [x] When copying an Agent link 'JSON' of an attribute and pasting it in a new Agent link of another attribute:
- only the Agent ID parameter get's visible the first time
- only when pasting it a second time, the other parameters become visible
- when first selecting the Agent ID and than paste the full JSON it works directly

- [x] When adding the 'Query parameters' parameters, the Agent link field goes blank (in this case for a HTTP agent)

- [x] Drag and drop: suppose the order of items is 1, 2, 3; I drag 3 in between 1 and 2; the new order becomes 3, 1, 2. The expected order is 1, 3, 2. Moving and item up, in between two items, always moves it 1 too high.

**Comment by pierrekil** [comment]
- [ ] the JSON button bottom line is hidden: 
![Screenshot 2021-09-10 at 15 42 34](https://user-images.githubusercontent.com/11444149/132862793-acd18d37-b8fa-4bf1-ac8f-a71b1a631d94.png)
![Screenshot 2021-09-10 at 15 43 28](https://user-images.githubusercontent.com/11444149/132862854-3a9bd6f9-4ce1-4767-9f58-6842b4a24ecb.png)
- [ ] Add margin to helper text for Agent link parameter 
![Screenshot 2021-09-10 at 15 43 50](https://user-images.githubusercontent.com/11444149/132863008-abb62eec-b218-40f7-abff-c2dd91e27430.png)

**Comment by richturner** [comment]
What browser was this? Didn't see this behaviour on Windows Chrome

**Comment by pierrekil** [comment]
iOS, Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by pierrekil** [comment]
JSON button issue dissapeared :-)
