### ISSUE TITLE
openremote/tileserver

### ISSUE THREAD

**Issue by aivorra** [openremote/openremote#483]
Hi, I an staring with openremote. I want to work with tileserver but I get this error: 

Pulling tileserver-gl (openremote/tileserver:latest)...
ERROR: pull access denied for openremote/tileserver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

So, I went to docker hub and I can not find openremote/tileserver. There is openremote/tileserver-gl but I do not know if it is the right option.

**Comment by richturner** [comment]
Hi,

The `tileserver` is currently only necessary for serving raster tiles for the map; generally it should be ignored as there is an embedded `tileserver` in the `manager`.

Where did you stumble upon the `tileserver` image so we can try and improve documentation?

**Comment by aivorra** [comment]
Hi Rich, I want to change the map source.
I did "https://github.com/openremote/openremote/wiki/Developer-Guide%3A-Working-on-maps#downloading-maps-and-extracting-smaller-tilesets"
After that I did "https://github.com/openremote/openremote/wiki/User-Guide%3A-Custom-deployment#customising-the-map", with the same structure. I could change the logo.png with my own image. So I understand that the docker-compose.yml is OK.

My tree is:

openremote/
├── deployment
│   ├── manager
│   │   ├── app
│   │   │   ├── images
│   │   │   │   └── logo.png
│   │   │   └── manager_config.json
│   │   └── keycloak.json
│   ├── map
│   │   ├── mapdata.mbtiles
│   │   └── mapsettings.json
└── docker-compose.yml

My mapsettings.json is the same of "https://github.com/openremote/openremote/blob/master/manager/src/map/mapsettings.json", I only changed center, bounds and zoom.

So, probably I'm forgetting something important to apply my map.

I'm still seeing Rotterdam.

Thank you in advance.

**Comment by aivorra** [comment]
Hi Rich, I started from the scratch again and I could make it works.

I guess that my problem was that I mix the docker-compose from different source. I try to use the deploy.yml.

Now It's working even with style.

This is my docker-compose.yml:

version: '2.4'

volumes:
  temp-data:

services:

  proxy:
    image: openremote/proxy:${PROXY_VERSION:-2.1.2.3}
    restart: always
    depends_on:
      manager:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"

  postgresql:
    restart: always
    image: openremote/postgresql:${POSTGRESQL_VERSION:-9.6.21.0}
    volumes:
      - temp-data:/tmp

  keycloak:
    restart: always
    image: openremote/keycloak:${KEYCLOAK_VERSION:-13.0.1.0}
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      KEYCLOAK_FRONTEND_URL: ${EXTERNAL_URL:-https://192.168.1.224}/auth
      KEYCLOAK_PASSWORD: ${SETUP_ADMIN_PASSWORD:-secret}

  manager:
    restart: always
    image: openremote/manager:${MANAGER_VERSION:-latest}
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      DEV_MODE: ${DEV_MODE:-false}
      SETUP_ADMIN_PASSWORD: ${SETUP_ADMIN_PASSWORD:-secret}
    volumes:
      - ./deployment:/deployment


Thanks a lot.
