### ISSUE TITLE
Stay in asset editing mode

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#49]
When changing attribute configuration in an attribute (in edit mode) and saving (eg. add 'show on dashboard'), state should remain in edit mode. It now goes back to view mode.

**Comment by christianbauer** [comment]
If you want to continue editing after adding an attribute, just don't click Save until you are done?

**Comment by pierrekil** [comment]
even when adding attributes for different assets

**Comment by pierrekil** [comment]
Solved. I missed the proper sequence.
