### ISSUE TITLE
Rules: make 'any of this type' trigger with each asset meeting the condition

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#491]
Current a LHS condition with 'any of this type' only resets the rule when 'none of this type' is met. How can we set the reset condition in an intuitive way?

Example of a user: https://forum.openremote.io/t/rule-triggered-by-timer-not-implemented/872/5

**Comment by richturner** [comment]
Probably related to #434 which was closed, I've reopened it and this comment should probably be moved there

**Comment by pierrekil** [comment]
part of #434
