### ISSUE TITLE
Open arrow wrongly configured for JSON forms

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#504]
Make identical to other arrow behavior:
- [ ] Position on left (not right)
- [ ] Point to right when closed
- [ ] Point down when opened
![Screenshot 2021-10-05 at 09 14 13](https://user-images.githubusercontent.com/11444149/135977346-917db756-dfc5-42e2-add6-7f9c9cb65edf.png)

**Comment by richturner** [comment]
JSON forms actually follows material design specification

**Comment by richturner** [comment]
Also I created a new component called `or-collapsible-panel` for this functionality

**Comment by pierrekil** [comment]
Make sense to be consistent on 'icon/button' showing the 'behavior when pressing', as we also do that with the 'Modify' and 'View' button on asset page. So change arrows in front of attributes (leave in front)
- [ ] Point down, when collapsed
- [ ] Point up, when uncollapsed
