### ISSUE TITLE
Map doesn't update all tiles

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#516]
<img width="2355" alt="Screen Shot 2021-10-25 at 18 39 56" src="https://user-images.githubusercontent.com/11444149/138736006-3a7ee470-3952-40b7-9023-6b46bba37040.png">

**Comment by richturner** [comment]
The `mapsettings.json` is not appropriate for the `demo` `mapdata.mbtiles`:

https://github.com/openremote/deployments/commits/demo/deployment/map/mapsettings.json

I made a quick update but the bounds and zoom levels should be confirmed against what is in the `mapdata.mbtiles`
