### ISSUE TITLE
MQTT Client (Service User) ability to write to `READ_ONLY` attributes

### ISSUE THREAD

**Issue by richturner** [openremote/openremote#517]
Should MQTT clients be able to write to `READ_ONLY` attributes like agents can

**Comment by richturner** [comment]
Relates to #409

**Comment by richturner** [comment]
Should `READ_ONLY` configuration item just be for `UI` purposes? Otherwise we need to differentiate between users using the `Manager UI` and `MQTT clients`; technically both write attributes through the `ClientEventService` so there is no difference between them at present.

**Comment by pierrekil** [comment]
Yes, only using READ_ONLY for UI makes sense. So only to prevent writing attributes, you wouldn't 'normally' change, eg. a capacity or meta item. If you can access the 'Modify' function you coud still change it.
