### ISSUE TITLE
FCM Notification enhancements

### ISSUE THREAD

**Issue by ebariaux** [openremote/openremote#52]
Currently when a notification is sent, the alert notification is stored in database and a "trigger" notification is sent using FCM. If the send to FCM fails, it is never re-tried and the trigger will only happen when a new notification is sent.

- [x] 1. retry mechanism should be implemented

- [x] 2. additional status for delivery to FCM should be added (current DELIVERED status means notification has been ack'ed by user).

- [x] 3. notification sending should be isolated in different object to ease testing

- [x] 4. proper testing must be implemented

- [ ] 5. notification sending (call to FCM) is done in synchronous way in user exposed method and could block rule thread for long time. Communication should happen in async way.

**Comment by christianbauer** [comment]
1. We now retry to deliver the "pick up signal" to a user's registered FCM devices repeatedly. When a new notification is inserted and PENDING, we iterate through all PENDING, and if we can at least reach one of the user's FCM devices, we set all PENDING to QUEUED.

2. Changed DeliveryStatus to PENDING (not successfully contacted FCM), QUEUED (successfully delivered FCM signal, user should see the notification), ACKNOWLEDGED (user has dismissed the notification).

3. Created FCMDeliveryService that encapsulates FCM.

4. Done some more tests both interactive and automatic, everything looks good.

5. Not done, also the ACKNOWLEDGED notifications must be manually cleaned up in manager UI. We should implement a reaper thread that deletes ACKNOWLEDGED notifications after a configurable time, e.g. 24 hours.

**Comment by richturner** [comment]
- [ ] Ensure FCM API is being correctly used (backend) - 4hrs
- [ ] Cleanup acknowledged notifications in manager (backend) - 4hrs
- [ ] Add support for sending arbitrary FCM notifications to topics (backend) - 8hrs
- [ ] Add support for data payload in notifications (backend) - 8hrs
- [ ] Add support for consoles to subscribe to topics (Android and iOS) - 16hrs
- [ ] Add support for silent notifications (data only) to make the consoles perform some action - 16hrs

**Comment by richturner** [comment]
FCMDeliveryService now using Firebase Admin SDK
