### ISSUE TITLE
JSON to GEO JSON

### ISSUE THREAD

**Issue by javobarra** [openremote/openremote#524]
Hi! I followed the Weather Example with OpenWeather. OpenWeather sends Location but not in GEO JSON point format. The "Weather Asset" profile has a location attribute with this type of data. Please anybody help me for translate JSON to GEO JSON???is it the only way with Attribute Links for resolve that?? Thanks!

**Comment by richturner** [comment]
Please use the [forum](https://forum.openremote.io) for help.
