### ISSUE TITLE
When creating new realm, no users page shown

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#525]

**Comment by richturner** [comment]
Not much info here but...

Thought I'd created an issue about this but I think it is related to the fact that you need super admin permission to view users.

**Comment by pierrekil** [comment]
When I login as super admin in staging.demo and create a new realm and select it, the menu shows the 'users' option, but when selecting it shows a blank page.

When realm is already provisioned, the user page exists, eg 'X2' or 'NC'

**Comment by richturner** [comment]
I tracked this down,, it's actually caused by the gateway asset that was created which then auto created a service user and this service user causes the error on the users page.

Will push a fix tomorrow (weds).
