### ISSUE TITLE
Gateway secret

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#527]
When service user secret is regenerated on the users page (for gateway asset), it doesn't update the Client secret at the gateway asset

When the Client secret on the gateway asset is changed (which is possible as it is a write attribute), it doesn't change on the users page.

Should Client ID and Client Secret on Gateway be 'read only' in UI?

**Comment by richturner** [comment]
Gateway service user used to be created with an `internal` attribute which stopped it showing up on the service user page; sounds like this has been broken. As gateway asset was created before service users the idea was that you interact with the gateway asset, but for consistency authentication should be managed using the standard service user UI.

**Comment by richturner** [comment]
Made client ID read only but implemented the ability to change the client secret attribute and that will auto update the service user secret.

**Comment by pierrekil** [comment]
When regenerating secret on service user page, it should also update on gateway asset page

**Comment by richturner** [comment]
I can add that capability but be aware the gateway service user is
only.visible to super users who should know not to mess with it.
