### ISSUE TITLE
Can't add new user on users page

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#529]
Not sure about root cause...

**Comment by bagherfathi** [comment]
my 10 days ago installation work well but yes, I can't add a new user about 3 days ago update, I have tested on two different server,s and on both raised the same error:
Uncaught (in promise) TypeError: t.realmRoles is undefined
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    u https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    _invoke https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    k https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    u https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    promise callback*n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    o https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    o https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    _invoke https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    k https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    async https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    set https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    t https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    u https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    _invoke https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    k https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    u https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    promise callback*n https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    o https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    o https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    _invoke https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    k https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    async https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    value https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    set https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    e https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    u https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    _invoke https://localhost/manager/bundle.dbf997f3897040575af9.js:2
    k https://localhost/manager/bundle.dbf997f3897040575af9.js:2
bundle.dbf997f3897040575af9.js:2:3865152
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654
Access token update success, refreshed from server: false 2 bundle.dbf997f3897040575af9.js:2:2559654
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored. token
Access token update success, refreshed from server: true bundle.dbf997f3897040575af9.js:2:2559654

**Comment by richturner** [comment]
@bagherfathi @perrochiba-cpu Please try the latest docker image

**Comment by bagherfathi** [comment]
thank you @richturner , it works well
