### ISSUE TITLE
Set the solar.forecast key for Demo using Github secret

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#542]

**Comment by aktur** [comment]
Where I can find an example how the solar.forecast key is used?

**Comment by Miggets7** [comment]
[manager/src/main/java/org/openremote/manager/energy/ForecastSolarService.java](https://github.com/openremote/openremote/blob/95e495be2e2bedd255090927ad5673798da3c9de/manager/src/main/java/org/openremote/manager/energy/ForecastSolarService.java)

**Comment by aktur** [comment]
Closed by f14390e in openremote/deployments repo.

**Comment by pierrekil** [comment]
Can you use the other key for both demo and staging.demo?

**Comment by aktur** [comment]
Key updated.
