### ISSUE TITLE
Issues with update core dependancies

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#545]
- [ ] Multiattribute picker stopped working. It only stores last selected attribute
- [x] Restricted access: selected assets for restricted user are not stored. Selection is '0' when navigating back to the user
- [x] Data export people not accessible via menu

**Comment by richturner** [comment]
@pierrekil I cannot re-create the first or second items, please provide a bit more info.

Multi-attribute picker is configured for `or-chart` component and `data export` page and in both places I see the multi select list with checkboxes and upon clicking add all selected ones are added.

Similarly when I go to the user page and modify the linked assets changes are correctly stored.

**Comment by pierrekil** [comment]
Multi-attribute picker issue: reproduce:
- testing on staging.demo 
- go to insights, add attributes to chart
- select attributes 'Ozone level' for 'Environment monitor' - 'Eendrachtsplein' as well as for 'Environment monitor' - 'Kaappark', and press 'ADD'
- Only the 'Ozone level' for the last asset 'Kaappark' is shown
- When adding attributes again, the initially picked attributes are not shown as selected
- Only the selection for the last asset is used, while it seems not to be storing any earlier selections (on other assets, or on an earlier session using the attribute picker)

Can't reproduce the 2nd issue either

**Comment by richturner** [comment]
The expectation that attribute are re-selected when you click add again seems strange to me especially as there is the delete button next to each attribute. Add implies you are adding not altering existing selection.

**Comment by richturner** [comment]
For now I've implemented as it was and as you describe but I think my previous comment is still valid.

**Comment by pierrekil** [comment]
The attribute picker doesn't allow selecting attributes of multiple assets, only from a single asset. It also deletes the previous selected. Is staging updated already?

Expected: 
- When I have 3 attributes selected and displayed, and click 'add' again I expect to be able to see what I have already selected and be able to add more. Otherwise I wouldn't be sure what I have already selected. 
- Indeed I can delete attributes in the modal but that's still intuitive if I also see what was previously selected.

**Comment by richturner** [comment]
Staging only updates once a day at approx. 1am GMT it looks like.

Regarding delete I was referring to the delete button next to each attribute outside of the dialog:

![image](https://user-images.githubusercontent.com/7072278/143484506-e7457386-8342-4290-a87f-8bdd0ca6577f.png)

If you want to keep the behaviour you are describing then I suggest changing the name of the button from `Add Attribute` to `Select Attributes` which would be more appropriate.

Alternatively keep `Add Attribute` and then grey out or hide attributes already added.

**Comment by pierrekil** [comment]
Good suggestion!
