### ISSUE TITLE
Chart and attribute panel setting not saving

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#548]
None of the settings of the chart and attribute panel on the Insights page is saved in local storage, per Realm:
- selected attributes
- timeframe
- period
- day/time
- delta
- decimals

When navigating away and coming back to the insight page it's empty. Note that local storage is per realm, so realm switching will change attributes in graphs and attribute panel.

**Comment by richturner** [comment]
Fixed by 31f024a1d6cf7212fb3963a90977637f900c9ee3
