### ISSUE TITLE
Newly created user with read/write role get's empty page for roles and users

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#559]

**Comment by richturner** [comment]
Can you please provide steps to reproduce....I cannot recreate

**Comment by pierrekil** [comment]
Reproduce:
- I create a new user in a realm and give them all rights
- Next login as that user
- Both 'users' and 'roles' pages are empty
![Screenshot 2021-12-10 at 10 56 25](https://user-images.githubusercontent.com/11444149/145555158-856fdd5c-823f-4117-a232-b945e8234f00.png)
![Screenshot 2021-12-10 at 10 58 27](https://user-images.githubusercontent.com/11444149/145555271-967984a8-b0a5-41a6-8a7d-3c8e18b18ed2.png)

**Comment by pierrekil** [comment]
This new user can create another new user in his realm, but can't open the user on the user page, once saved.

Reproduce:
- I create a new user in a (new) realm and give them all rights
- Next login as that user
- On the user page that user creates another new user and saves it
- You can't uncollapse that new user to change it's settings. The username is 'grey'
![Screenshot 2021-12-13 at 09 27 21](https://user-images.githubusercontent.com/11444149/145778105-52bdcd39-0d80-413d-bf6f-bc4a300d3575.png)
