### ISSUE TITLE
Detecting asset problems and maintenance workflow

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#56]
E.g. motion sensor is stuck in ON position if there was no update in 24 hours. 

Maintenance workflow:

- go into manager and disable the scene timer or disable alarm for all scenes
- contact the maintainer/installer and the user and tell them what’s wrong. this step should also be captured in our manager tool, so the next guy on the phone can look up the issue history (CRM)
- when a manager logs in, show a TODO list of pending maintenance issues

Should this be part of ProtocolConfiguration or an attribute linking option?

Actions: 
- Easy: Store problems in DB, expose on webservice for external monitoring (Pingdom)
- Difficult: Send email, notify admin, notify user(s), requires work on notification system
- Best: Provide CRM-like functionality to improve maintenance workflow, see #58

**Comment by pierrekil** [comment]
Define a rule for attributes linked to sensors, which describes abnormal behavior, and have this flagging an attribute: ‘requires attention’, as well as ‘urgency level’ (1-3). With this we could always create a report with overview of assets (with lowest urgency level) requiring attention. This limits notifications. Critical assets (higher urgency) could always trigger individual notification: email / sms
