### ISSUE TITLE
Map: add controls: center on location, set marker

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#562]
As a user I want to center on my location when on mobile, so that I can quickly navigate to my area.
As a user I want to place the marker of an asset, so that the correct location for the asset is stored.

Version one has the following controls that can be enabled on the or-map component:
- [x] Center on location button pans the map to the location of the user.
- [x] Center on asset button (marker icon) pans the map to the location of the asset
- [x] Address bar: on select from list/enter center on address
- [x] Place or reposition a marker (when writing the an asset location attribute) by long pressing on the desired location on the map.

Added:
- [x] Automatically center map on asset on the 'asset view page' when opening that page
- [x] Automatically center map on asset when editing it's location in the 'asset modify mode'

**Comment by pierrekil** [comment]
- [ ] Automatically center map on asset on the 'asset view page' when opening that page
- [ ] Automatically center map on asset when editing it's location in the 'asset modify mode'

**Comment by pierrekil** [comment]
Still not visible in staging demo / demo
