### ISSUE TITLE
Asset tree filter extension with labels

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#571]
First feature: select an attribute and filter on a value condition (=, >, <, between...)

See [spec](https://docs.google.com/document/d/1LZOKCIng-_mssSwULkTBFgeaR5Okjo6I1gM3VEAqHvE/edit#heading=h.s889wtt29qif)

**Comment by jvervier** [comment]
Hi @DonWillems ,
Is this Issue still open since the merge has been done? Or do we keep it for other points?

**Comment by pierrekil** [comment]
Hi, there are still 2 minor styling issues, which kept it open:
- aligning the 'x' vertically
![Screenshot 2022-06-01 at 09 06 19](https://user-images.githubusercontent.com/11444149/171347918-574547df-9723-4b6f-afd4-a9082da34fa6.png)

- add some vertical space between 'Attribute value' input field and 'Filter' button
![Screenshot 2022-06-01 at 09 06 56](https://user-images.githubusercontent.com/11444149/171348019-9cd45dd4-5f60-4add-bf9b-6f20d761904a.png)
