### ISSUE TITLE
Manager Config in UI

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#575]
First add Manager Config settings page with JSON text field
Next adjust to enable it to show in Form editor

**Comment by NealGeilen** [comment]
Development Progress 

### UI Components

## Individual components per setting category 
- [ ] Assets / Agents
- [ ] Map
- [ ] Realms

# Components that could be helpful to create
- [ ] Image uploader that shows the current image. 
- [ ] #823 

### API
## Endpoints
- [ ] Uploading images for the logo's
- [ ] Getting the `mapsettings.json`
- [ ] Saving `mapsettings.json`
- [ ] Saving `manger_config.json`
- [ ] Uploading the map itself

**Comment by DonWillems** [comment]
- [ ] Increase save button margin-left to 15px;
- [ ] Make styling exactly the same as e.g. Users and Roles. Header and spacing etc.
- [ x ] Chevron same as on modify asset: --or-icon-width:20px; --or-icon-height:20px; margin-right: 6px; margin-left: -5px;>>> nvm this, should be set for the expandable header in modify asset too, will do separately
- [ ] Header title: not strong
- [ ] Padding of panel-content: 0 24px 24px;
- [ ] Remove bottom margin of delete button 
- [ ] or-mwc-inputs should have padidng: 10px 0px
- [ ] Realm title should be Application title, or Manager title
- [ ] Is there a max to image size?
- [ ] Add hover effect to images to show it can be edited. Remove current pencil icon.
- [ ] Increase margin between color and label to 10px
- [ ] Add cursor pointer to colors
- [ ] Make the menu items match the names in the actual menus
- [ ] Why are not all secondary menu items in the options list?
- [ ] When deleting a realm styling item, add dialog to confirm before deleting.
- [ ] When adding a realm styling item, open it.
- [ ] Add padding to bottom of page

**Comment by pierrekil** [comment]
- [ ] There is too little space above 'Realms' header and below 'DELETE' and 'ADD REALM CUSTOMISATION' (now no space). 
- [ ] The left and right indents of main icon/title and panels do not correspond to other pages.

Use same styling as e.g. Users page, Individual user page  and Roles page. Header and spacing etc. (point 2 above). Let's check with Don as maybe conflicting with other remarks above?
