### ISSUE TITLE
Add configuration item Agent link breaks

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#580]
When adding the configuration item agent link, the manager breaks.
![Screenshot 2022-01-12 at 16 58 16](https://user-images.githubusercontent.com/11444149/149175673-e7b53475-2a7a-41e5-99aa-4f5bb2ff8c93.png)
![Screenshot 2022-01-12 at 16 45 24](https://user-images.githubusercontent.com/11444149/149175693-f0342f18-ba31-4031-9f2a-513bcaa23ae2.png)

**Comment by pierrekil** [comment]
Configuration item 'Agen link' has changed back from a form into an JSON input

**Comment by richturner** [comment]
This was done deliberately as a temp solution

**Comment by BlackHawk1912** [comment]
@richturner Is there a documentation of how to use this input field? Specifically how to add an MQTT Agent with just this input field?

**Comment by richturner** [comment]
Unfortunately you'll need to look at the source code for the Agent Link:

https://github.com/openremote/openremote/blob/master/model/src/main/java/org/openremote/model/asset/agent/AgentLink.java#L47

The fields of the JSON object for Agent Link will match the agent link class field names.

I'll try and get the json forms bug fixed tomorrow as that is a much simpler way of doing this (unfortunately projects have got in the way until now) :-)

**Comment by richturner** [comment]
`AgentLink` UI should be working again in latest manager docker image (dated after this post)
