### ISSUE TITLE
Adding attribute sometimes breaks

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#581]
Adding an attribute to an asset sometimes breaks. 
It always happens for the 'weather asset' in staging demo. Seems to be for assets which already have an agent link in one of the attributes. Might be resolved together with #580

panel shows translucent:
![Screenshot 2022-01-12 at 17 05 23](https://user-images.githubusercontent.com/11444149/149176826-48abfe74-f4a4-4a93-89b0-d33816b64ae3.png)

**Comment by qyh405** [comment]
Same issue happened in my side.

**Comment by richturner** [comment]
Seems to be an issue with updated versions of dependencies will pick this up in the next couple of days

**Comment by BlackHawk1912** [comment]
Hi Rich, could you let us know when its updated? Or is there a workaround because I am currently setting up thingsboard but can't process any further right now.

**Comment by richturner** [comment]
Yes I will post here when the issue is closed.

**Comment by richturner** [comment]
Same issue as #580

`Agent link` UI should now be working again
