### ISSUE TITLE
Console menu icon improvements

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#588]
- [ ] animate menu to come in from bottom (when icon at bottom) or top (when icon at top)
- [ ] create space between menu icon and menu (like EHV app)
- [ ] Option in appconfig to add title (Bold)
- [ ] Do not grey out background and menu icon when menu is opened
- [ ] Listed items closer together
- [ ] In between lines should have same indent on the right (currently 0) as on the left

**Comment by richturner** [comment]
@pierrekil @Miggets7 To have improved control over positioning of menu item it might be worth switching to `left, right, bottom, top` values
