### ISSUE TITLE
Docker error!

### ISSUE THREAD

**Issue by IstiyakV** [openremote/openremote#591]
openremote-master>docker-compose -p openremote up
openremote_postgresql_1 is up-to-date
openremote_keycloak_1 is up-to-date

ERROR: for manager  Container "b2e8737059b0" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by richturner** [comment]
Hi, this is something for the forum, please include the log output as it is difficult to assist without it:

https://forum.openremote.io
