### ISSUE TITLE
Permissions and roles for non-superusers

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#6]
- [x] As a user, I want to list, create, update and delete tenant/realms so all data can be isolated for each tenant (5pt).
- [x] As a super-user, I want to list, create, update and delete users for each tenant/realm (5pt).
- [x] As a user, I want to assign roles to users (3pt).
- [ ]  Define roles for super/tenant administration, how do we handle superusers OF a realm.
- [ ] Resolve any issues with login of !superuser in Manager UI, currently there are no role permission checks in the code and the UI breaks randomly as server calls fail.

**Comment by christianbauer** [comment]
This is now implemented, although roles for super/tenant administration are not yet defined.

**Comment by christianbauer** [comment]
- [ ]  Define roles for super/tenant administration, how do we handle superusers OF a realm.

**Comment by pierrekil** [comment]
Updated and replaced by #568
