### ISSUE TITLE
History graph falls back to default attribute

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#602]
Behavior:
- Select another attribute than the default attribute in the History graph
- The graph will show the related data
- When new data is entering the system (through an agent), the graph will fall back and show the data of the default attribute.
- The selected attribute still shows the one you have selected

Expected:
- Always show the data of the selected attribute

**Comment by jvervier** [comment]
Hi @pierrekil and @DonWillems 
I noticed in the description "(through an agent)", it's also the case for information when we update directly into the attribute field and send the new value manually.

**Comment by pierrekil** [comment]
@jvervier, this issue seems related to the updates on history graph?

reproduce:
- navigate from an asset page which has one or more attributes with 'store data points'
- the asset page looks as expected
- navigate to a page without any attribute with 'store data points'
- the asset page is duplicating/overlaying UI elements:
<img width="1218" alt="Screen Shot 2022-04-15 at 09 04 26" src="https://user-images.githubusercontent.com/11444149/163536952-f7caafd7-a054-4dd4-8cb1-754b4391bf30.png">

**Comment by jvervier** [comment]
Hi @pierrekil 

The fix wasn't include any css changes. But we already noticed this issue depending on a specific scenario and also asset relation.

I've got a branch without that fix. I'll check if issue is reproducable or not and investigate.

**Comment by jvervier** [comment]
Hi @pierrekil,

Found reason with an uncovered case.

I restest also the initial issue and the fix is still working.

I'm pushing this on a branch and ask for PR to Richard.

**Comment by jvervier** [comment]
Reason :

As callback's (on onRenderComplete) are not reset when selecting a new asset in asset tree, we need to check if history select dom elem exists.

A branch is created and PR will be there soon

**Comment by jvervier** [comment]
I'll try to join Richard to discuss a more general question in addition to this first fix
