### ISSUE TITLE
Rules scheduler not fully working

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#613]
Scheduler in rules can be edited, but not all changes are saved. 
- [ ] when selecting 'Plan an occurence', beginning and end time are not saved
- [ ] when selecting 'Plan a repeating occurence' the option 'Repeat occurrence every' is not saving the selected days.

**Comment by jvervier** [comment]
Hi @DonWillems and @pierrekil 

First issue (beginning and end time) was easy to solved, the second seems more linked to general behaviour of or-mwc-input of CHECKBOX_LIST type. I'm busy on this last point as it shouldn't also have side effect on other place where it's used.

Regards

**Comment by jvervier** [comment]
Find the reason for second point of the issue. CHECKBOX_LIST is only used in that place but it seems the waited event emitted on validity side is not containing what or-mwc-input is really emitting in term of data.
I'll propose a new simple way.

**Comment by jvervier** [comment]
Hi,
Fix has been done on branch "bugfix/613-scheduler-not-fully-working". Need maybe to demo to @DonWillems before doing PR.
