### ISSUE TITLE
Improve CSS styling approach (deprecation warning of Chrome for 2018)

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#62]
Fix deprecation warning for 2018 on:
- Chrome

Login screen first displays without styling for a split second:
- iOS Console
- Firefox

Manager UI is already switched to new webcomponents.js styling API, other apps are lagging. We need to have a simple strategy for CSS features we need:

- CSS3 variables on all interesting browsers for colour themes and other simple placeholders

- Are we happy with Polymer 2 CSS mixin support? Or is that in webcomponents.js polyfill?

- How are global styles used?

- How are styles applied to the shadow DOM template on a component level, how do global styles and mixins best support customisation of a subset of component styles.

**Comment by christianbauer** [comment]
Implemented in smart home example app.
