### ISSUE TITLE
Updating a ruleset linked to a template asset in the manager UI deletes the ruleset

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#64]
Edit a ruleset linked to a template asset, click Update, you get a 400 and the ruleset is gone.

**Comment by aktur** [comment]
This was the same with regular drl's and Michael got it repaired. IMHO he can do this for drlt pretty fast.

**Comment by Miggets7** [comment]
As which Role are you logged in? By Update I guess you mean `Save ruleset`?

**Comment by christianbauer** [comment]
Yes, also just enablung/disabling and then saving without editing the rules text should restart the RulesEngine.

**Comment by Miggets7** [comment]
I can't reproduce it. The steps I took where logging in as Admin, pick a asset, add a ruleset and pick a Template asset, and enter rules content. Then I hit Save ruleset and the ruleset is added. Later I enable/disable, change some text and hit Save ruleset again. Later I hit Save ruleset without changing something. Still everything goes well. I've tested it in FireFox and Chrome.

**Comment by aktur** [comment]
Creating a new ruleset is workaround this bug, this is why I was putting my rules always by hand before you've repaired it. To reproduce this bug you must edit template rules as they are built into the manager, just go to priority flights template, hit edit, add a space and hit save.

**Comment by Miggets7** [comment]
Can't reproduce it whit existing rulesets. Also tried it with priority flights template.

**Comment by aktur** [comment]
Try it on a standalone server (staging or development if you dare ;)

I've just tried it on my test rackserver with the latest pull and got:
OpenRemote Inc.

Request failed. Got response status 404 but expected one of [200]. To repeat the request later, reload the page

**Comment by Miggets7** [comment]
Just tested it on the priority flights template, and it's not happening anymore on staging.
