### ISSUE TITLE
Console: Replace consoleappconfig with console_config.json

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#642]
The console_config will, just as manager_config, contain all configs for the different realms. This config overwrites what might be set in the info.json of an individual app.

Controls the settings screen behaviour for a host, JSON keys:
```
showAppTextInput [boolean] - Show app text input instead of drop down (user must correctly enter app name)
showRealmTextInput [boolean] - Show realm text input instead of drop down (user must correctly enter realm name)
app [string] - Load a specific app (don't allow choice)
allowedApps [string[]] - List of allowed apps (ignore apps that are actually available and use this list instead)
apps [object]
    <APP_NAME> or 'default': [object]
          info [object] - same structure as App Info (info.json)
              consoleAppIncompatible [boolean] - If set to true don't show in list
              realms [* | string[]] - List of realms that can be used with this app
              providers [* | string[]] - List of console providers the app wants to/should use
              description [string] - Description of the app
```
	
- [ ] Remove OR_CONSOLE_APP_CONFIG_DOCROOT and CONSOLE_APP_CONFIG_PATH (just use OR_CUSTOM_APP_DOCROOT)
- [ ] Remove consoleappconfig from repo(s)
- [ ] Document 'console_config.json'
- [ ] Rename ConsoleAppResource -> AppResource
- - [ ] Rename getInstalledApps -> getAppInfo and make this public with return type of AppInfo[] (see below)
- - [ ] Update getAppInfo to return AppInfo[] collected from built in apps and custom apps
- [ ] Remove UI code that tries to load consoleappconfig and changes colour variables

If no console_config is present use the following defaults (using info.json of apps where possible):
```
showAppTextInput [boolean] - false
showRealmTextInput [boolean] - true
app [string] - Empty
allowedApps [string[]] - Empty (so all found apps should be available)
apps [object] - Empty
```
If realms and providers are not set in the app info.json then realms selection step is skipped. Do not initiate any providers

**Comment by ebariaux** [comment]
What if showAppTextInput = true and app is defined ?
Who has precedence ?
I would say if app is defined, skip app selection screen -> no input text

**Comment by DonWillems** [comment]
> What if showAppTextInput = true and app is defined ? Who has precedence ? I would say if app is defined, skip app selection screen -> no input text

Agreed
