### ISSUE TITLE
Undefined Documentation

### ISSUE THREAD

**Issue by WaleedAhmad0987** [openremote/openremote#644]
I've gone through the documentation and is obsolete and not clear cut. The recordings haven't been refreshed as the UI has additionally changed over the long haul. Compassionately update your documentation and add new recordings of help new developer effectively work through the documentation like clockwork. Featured part in the gave picture is the issue. 

![Capture](https://user-images.githubusercontent.com/43605158/158769839-d3e1d8d5-22cc-48c3-a505-a4147708b296.JPG)
https://github.com/openremote/openremote/wiki/Tutorial%3A-Open-Weather-API-using-HTTP-Agent
https://www.youtube.com/watch?v=mx9amWaItn0

**Comment by pierrekil** [comment]
This doesn't belong in GitHub issues, please post on forum. Mind that we do our best in open source to keep documentation up to date.
