### ISSUE TITLE
Add LIGHTWEIGHT option to AbstractAssetQuery.Include

### ISSUE THREAD

**Issue by christianbauer** [openremote/openremote#65]
This is a projection that returns a minified asset or list of assets with:

- asset ID
- each attribute's name, value and valueTimestamp
- No attribute type and meta items, no other asset details

The `<or-asset>` and `<or-asset-list>` frontend component asset loading can be done as:

- First query the assets you are interested in with projection `ALL` or the override set with  `<or-asset select="ALL_EXCEPT_PATH">`. This gets all type and meta information about your asset as well as initial values. Can be shown to the user at this point. 

- Then if `<or-asset auto-refresh="true">`, subscribe on the socket to AttributeEvents on the single result. Receive and send AttributeEvent to update the bound children of `<or-asset>`. 

- When `<or-asset-list>` has to be queried/refreshed again, it can use the `LIGHTWEIGHT` projection automatically (or make this configurable on an attribute as well.)

**Comment by richturner** [comment]
@christianbauer : The include probably needs some rationalising or needs to be more flexible. I needed to create an asset list where assets were grouped by type so I needed an include option like:

ONLY_ID_AND_NAME_AND_ATTRIBUTE_NAMES_AND_TYPE

The ResultSet supplied to AssetStorageService::mapResultTuple always contains ASSET_TYPE so maybe this should always be included along with other properties that don't sit inside attributes.

Include could be inverted:
```
public enum Exclude {
   PATH,
   ATTRIBUTES,
   ATTRIBUTES_META,
}
```
