### ISSUE TITLE
Unable to post a data to asset attribute

### ISSUE THREAD

**Issue by sw-dev-code** [openremote/openremote#654]
I'm trying to use Swagger to test posting the data to ThermostatAsset but I'm unable to do it due to "INVALID_VALUE_FOR_WELL_KNOWN_ATTRIBUTE" error.

Also, I would like to know what values should I set for `client_id` and `client_secret` fields in Swagger Authorize?

**Comment by richturner** [comment]
Please use the [forum](https://forum.openremote.io) for these discussions
