### ISSUE TITLE
Add color picker for light asset control

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#672]
A light asset requires a specific control UI (modal).

The color RGB attribute needs to enable:
- clicking a color visually 
- setting the RGB values with 0-255 values
- control the color saturation, either within the color picker or as an additional slider showing the resulting color (from white to fully saturated colour)

Following attributes remain separate attributes (unchanged):
- Colour temperature attribute remains a separate attribute with number (K, range 1,000-10,000).
- On/off
- Brightness  (%)

**Comment by jvervier** [comment]
Hi @pierrekil and @DonWillems,

Are we looking for a colour picker looking like this ?

<img width="504" alt="image" src="https://user-images.githubusercontent.com/10142800/164982537-8470471d-60db-4765-8001-a79019a6764b.png">

**Comment by jvervier** [comment]
And what about using this library who seems letting the capacity to add and use needed components?
https://iro.js.org

**Comment by pierrekil** [comment]
This one looks good if we can use it: color/saturation/dimlevel. How does it translate in RGB and dimlevel?

Verstuurd vanaf mijn iPhone

**Comment by jvervier** [comment]
Hi @pierrekil and @DonWillems ,

The Default picker with a wheel to selection colour/saturation.

For the dim level, this picker is proposing a slider (see Default from https://codepen.io/rakujira/pen/XWbgwYm?editors=1011) where it play with brightness of the colour but it doesn't export the value in a separate output than the RGB. So it doesn't fit the separate dim level need.
Available sliders to complete the wheel colour selection are : 'saturation', 'value', 'red', 'green', 'blue', 'alpha' or 'kelvin'

Output can be RGB Colour : https://iro.js.org/color_api.html#supported-color-formats

I'll look for other alternative including dim level is a separate output.

**Comment by jvervier** [comment]
It seems we can extract the dim level from the hsv output value (output available from the library).
By this way :  
`var level = Math.round(color.hsv.v/100*255);`

where 255 is the highest value of the dimlevel of the device

**Comment by jvervier** [comment]
Hi,

Iro.js is proposition sliders for R, G, B. So it's fully possible. We can handle to add a input field to manually set the value for each one.

So here, sorry but I prefer to put the context clearly for the actual issue : 
The idea will be to review the RGB attribute type input such that we propose a "three sliders" input to set RGB instead of the actual default colour picker (rectangle).
Should we consider to keep the rectangle colour picker for other usage and so consider to create an new or-mwc-input type for RGB?

**Comment by pierrekil** [comment]
Still some confusion I think. Ignore all the mentioned asset types. For the RGB attribute, we like to have the default implementation, so with output in RGB attribute:
![Screenshot 2022-05-05 at 09 28 48](https://user-images.githubusercontent.com/11444149/166879566-153f8962-37d4-46b2-b709-11f941a76641.png)
