### ISSUE TITLE
Realms: ability to delete realm

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#683]

**Comment by WebDust21** [comment]
Regression?  Delete Realm does not work with the latest OpenRemote.

Web UI -> Realms -> [select Realm] -> Delete Realm -> [key in the Realm name] -> ["OK button" automatically enables] -> click OK -> nothing happens.  No network traffic (no Post/Get/Delete: none!), and the dialog remains open.

**Comment by DonWillems** [comment]
Thank you for reporting! We'll look into it.
I'm not able to test at the moment, but I remember there being an issue when deleting when there are assets and users present in the realm.

**Comment by WebDust21** [comment]
I can confirm that there are no users or assets present in the realm I am trying to delete.

**Comment by WebDust21** [comment]
![image](https://github.com/openremote/openremote/assets/13712655/dbbce1be-6699-418d-baaf-b9ef7c751c79)
![image](https://github.com/openremote/openremote/assets/13712655/65ebfc0c-9c14-4592-900e-e813b8aeb4c9)

Is there anything else I can check/provide to help diagnostics/debugging this issue?

**Comment by DonWillems** [comment]
We can take it from here. Thank you for clearing that up.

**Comment by bitmorse** [comment]
having the same issue

**Comment by richturner** [comment]
@DonWillems I've created a PR to fix this:

https://github.com/openremote/openremote/pull/1230
