### ISSUE TITLE
docker-compose up ends with error.

### ISSUE THREAD

**Issue by aktur** [openremote/openremote#7]
My joy has stopped after docker-compose up:

michal@rutek06 ~/Developer/openremote/openremote> docker-compose up
Creating network "openremote_default" with the default driver
Pulling mongo (mongo:2.6)...
2.6: Pulling from library/mongo
8dddc0afbe0a: Pull complete
a3ed95caeb02: Pull complete
32eed1053be0: Pull complete
238985f894fd: Pull complete
c92ee4981033: Pull complete
432dada1b3de: Pull complete
8ae43fe32b85: Pull complete
03913f2c5b05: Pull complete
ERROR: failed to register layer: Untar re-exec error: exit status 1: output: no such file or directory

**Comment by christianbauer** [comment]
Michal, can you please try the latest updates and have another go at the quickstart from scratch? We should also give the new Docker for Mac a try. This replaces the Docker Toolbox we are using now.

**Comment by christianbauer** [comment]
https://forums.docker.com/t/where-does-docker-keep-images-containers-so-i-can-better-track-my-disk-usage/8370/20

**Comment by christianbauer** [comment]
I've tried the Docker Mac beta and almost everything works as you'd expect. The only problem is that the docker daemon doesn't listen on TCP/HTTP and the Java/Gradle library we are using for builds has broken unix socket support. So we can run stuff but not build without hacks. We'll have to wait for https://github.com/docker-java/docker-java/issues/537
