### ISSUE TITLE
building from source code using an ide

### ISSUE THREAD

**Issue by Nour-25** [openremote/openremote#705]
Question 
i'm trying to build and run the code source from an ide 
os : Ubuntu 20.04 lts
ide : iintellij
Java 17 JDK 
GIT
NodeJS]
yarn
Docker Machine is Deprecated so i have to use Docker image with tooling
this error appears 
docker run --rm -v `pwd`:/or registry.gitlab.com/openremote/openremote:master git status
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
so could any one please provide the full steps to build and run the code

**Comment by aktur** [comment]
I'm afraid that gitlab tooling is orphaned. It was abandoned long time ago in favour github actions. This kind of questions are better asked on [forum](https://forum.openremote.io)
