### ISSUE TITLE
Setting multiple attributes with one agent link breaks attributes history

### ISSUE THREAD

**Issue by Xunil32** [openremote/openremote#720]
Following the tutorial [Weather-API tutotorial with http agent ](https://github.com/openremote/openremote/wiki/Tutorial:-Open-Weather-API-using-HTTP-Agent) I have implemented a simple http agent retrieving a simple json  as:

```json
{
   "Timestamp": "2022-05-26T07:39:44.687879",
   "PLC_temp_int": 26.82591819779103,
   "PLC_temp_ext": 16.257565641068858,
   ...
}
```

Then I have implemented  a "thing" in the asset list with three attributes called respectively **PLC_temp_int** (number),  **PLC_temp_ext**(number) and **httpResponse**(json).

**httpResponse** has an agent link and a attribute link component, the attribute link has the following configuration:

```json
[
  {
    "ref": {
      "id": "5jyuiLIJ23NH0GODey2Boz",
      "name": "PLC_temp_int"
    },
    "filters": [
      {
        "type": "jsonPath",
        "path": "$.PLC_temp_int",
        "returnFirst": true,
        "returnLast": false
      }
    ]
  },
  {
    "ref": {
      "id": "5jyuiLIJ23NH0GODey2Boz",
      "name": "PLC_temp_ext"
    },
    "filters": [
      {
        "type": "jsonPath",
        "path": "$.PLC_temp_ext",
        "returnFirst": true,
        "returnLast": false
      }
    ]
  }
]
```
Everything works as expected and the attributes **PLC_temp_int** ,  **PLC_temp_ext** are populated parsing the attribute **Response**.

If I opne the asset in view or I try to create a graphig in the insight section tho I can't see the  **PLC_temp_int** and  **PLC_temp_ext** attributes in the history.

![image](https://user-images.githubusercontent.com/7924181/170447631-3e97817a-c096-4cd6-930f-2c0a30cafb59.png)

Is there a way to set multiple attributes with one agent link and still see the attributes in the history?

**Comment by pierrekil** [comment]
Please use the forum for these type of questions: https://forum.openremote.io Issues on GitHub are intended for technical issues or bugs (with details to reproduce)

**Comment by Xunil32** [comment]
Doesn't seems technical or an issue to the community? Not even a lack in documentation?

**Comment by richturner** [comment]
You need to add the Store data points configuration item to any attributes you want to see in the history chart; attributes that have an agent link are implicitly made available.

**Comment by Xunil32** [comment]
Thanks @richturner it did the trick!
I' going to open a PR for the weather tutotorial.

**Comment by pierrekil** [comment]
Just added it :-)
