### ISSUE TITLE
Console: issues testing default behaviour without configs

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#736]
- [x] when typing only 'demo' for the APP DOMAIN, an error page occurs (with an error which will not disappear anymore, even when closing the app). Expected behaviour, two options: 
 -- fill the blanks with .openremote.app to check whether this instance exists
 -- or immediately show the error message 'Cloud not connect to the domain. Please verify address (if this is less work).
 - [x] when typing https://demo.openremote.app it's immediately going to manager/master. Expected behaviour: check the available apps ('manager' in this case) and, as there is only one app, skip this step, automatically selecting 'manager'. However, still show a dropdown to allow for selecting a realm: 'master' or 'smartcity'.
 - [x] when typing https://staging.xx.openremote.app it's immediately going to manager/master. Expected behaviour: check the available apps ('manager' and 'xx' in this case) and show a dropdown with these two options.
 - [x] New 17/6 Android test version goes back to settings page when using testserver for APP DOMAIN and Manager-Smartcity realm, showing several errors

**Comment by Miggets7** [comment]
The second issue isn't possible, because there's no public endpoint where the app can request for the available realms. So the free text input will be presented so the user can fill in the desired realm.

The third one can't be resolved. The endpoint for requesting available apps is not public in the master branch.

**Comment by richturner** [comment]
Just spoken to @DonWillems about the confusion here; what @Miggets7 says is correct and connecting to existing managers will have limitations due to not having the new API endpoints and info/config files so some compromise of behaviour is needed which I discussed with @Miggets7 this morning.

Hopefully @DonWillems will bring @pierrekil up to speed :-)

**Comment by Miggets7** [comment]
It seems a json needs to be present on the realm after logging in:

> Error requesting 'https://test1.openremote.app/consoleappconfig/smartcity.json'

@richturner Should this json be present by default?

We talked about excluding apps with a file. For example the console_loader app needs to be excluded. Should be a separate issue I guess?

**Comment by richturner** [comment]
That path is the old console app config file which is named after the realm and should not exist any longer.

See skype chat discussion but to recap:

```
Whole process starts with host (if not a FQDN then assume .openremote.app suffix)
GET /console_config.json
If 404 then get list of apps from backend (/api/master/apps) - See Michael's branch where this is now a public endpoint
Present list of apps to user
When app selected then GET /app/info.json
```

**Comment by richturner** [comment]
This is the weird bit of code that was added to the manager app for some reason so that it can get the colours from the file.

I don't believe the manager fails to load if this file isn't found, is the console app code reacting to the 404 and then treating that as an error?

**Comment by richturner** [comment]
Maybe some confusion over the term app here; as I mentioned it is some code in the manager web app that makes the request for this resource and it then adjusts the manager colours to match if the file is found. If the file is not found then the manager web app works just fine.

The console code must be reacting to the 404 error; the console code should react to a 404 on the initial index page but should probably ignore errors causes by resources loaded by the page.
