### ISSUE TITLE
Image pushed to hub docker can be broken.

### ISSUE THREAD

**Issue by aktur** [openremote/openremote#744]
Discussion on the [forum](https://forum.openremote.io/t/not-found-error-when-accessing-manager-ui/1247) shows that there is a chance that a broken image can be pushed to the official docker registry. This is quite bad commercially as many potential customers wouldn't go to the forum but simply move to another IoT platform. The previous CI/CD pipeline contained UI test before pushing image to registry. Why this is dropped? A broken build can have many reasons.

**Comment by richturner** [comment]
The `latest` tag is no longer updated on `push` as it is intended to be updated on release and should be the latest released version. As `latest` is mentioned in lots of places I manually pushed this manifest to the registry the other day but clearly there was an issue.

As for UI testing then the work of Yu Hong will address that more thoroughly once his branch is merged,
