### ISSUE TITLE
Rules: When-Then: Add condition based on sunset/sunrise/set time

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#761]
As a user I want to trigger rules based on the time the sun comes up/goes down or a time set by me, so that actions can be performed at set times.

https://docs.google.com/document/d/1akcJGq-gQZkj4CoFfMtKtnzwQ24xdPvdXu_QsbOcWqg/edit#heading=h.g06k9a7lvww5

- [x] Add condition that lets the user select 'Sunset', 'Sunrise', or 'Time of Day'
- [x] Sunset and sunrise gives the user to select an offset in minutes (negative is possible)
- [ ] Sunset and sunrise requires location to be set (dialog) so that the system knows which times should be used
- [ ] Time of Day lets the user set hh:mm. This input field should also have the option to use the browser time selection input (.type="${InputType.TIME}")

Question to Rich:
Is 'Timer' the correct term for the option? Should it be something like 'Time trigger'? If so the 'alarm' icon would be more appropriate than the 'timer' icon currently used.

**Comment by richturner** [comment]
It's part of the `RuleCondition` (when) so the trigger is implied. Timer can indeed be changed to alarm though as timer is more suited to count downs

**Comment by aktur** [comment]
It would be nice to have more types of Twilight (dusk, dawn, civil etc.) On larger latitudes, like in Europe it is quite tricky to sync according to sunset and time offset. These types of twilights are usually supported by libraries (my version 2.5 controller does this). More info about twilights https://www.timeanddate.com/astronomy/different-types-twilight.html

**Comment by richturner** [comment]
Options now implemented are:

*Sun Position Trigger - location, position (SUNRISE, SUNSET, TWILIGHT_HORIZON, etc.) and optional offsetMins
*Duration - ISO8601 duration (e.g. PT1M)
*Cron - A CRON expression to determine when to trigger rule (this can be used to trigger at a specific time for each day)

**Comment by DonWillems** [comment]
It seems like the Twilight getset options are missing, and only getrise is implemented. Meaning you can only get the twilight start times during sunrise and not during sunset.
Additionally, it seems like a timezone should also be added (separate from location) as it uses the local timezone, which might not match the timezone of the chosen location. This should be set automatically based on the chosen location.

See this example: https://shredzone.org/maven/commons-suncalc/examples.html#twilight

**Comment by MartinaeyNL** [comment]
Frontend functionality is finished; `or-rule-trigger-query` component and necessary util functions have been added.
- Time of day with a HH:mm input field
- Sunset and sunrise options with offset field and location modal
- Twilight options with offset field and location modal

It's inline with the design/functionality mentioned in the google doc, as well as the checklist.
Code can be found in the `feature/761_time_condition` branch.
