### ISSUE TITLE
502 ERROR

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [openremote/openremote#780]
Hello All!,
I've been looking around and stumbled upon this fantastic project.
Unfortunately i was greeted by 502 Error.
Any remedy here?
Thanks,
-sdrshnptl
![image](https://user-images.githubusercontent.com/91423165/182296476-e1b7d495-ebd1-45da-a3b3-1504f795f52c.png)

**Comment by DonWillems** [comment]
Hi @OptifySudarshanPatil,

Do you still have this issue?

**Comment by OptifySudarshanPatil** [comment]
Hi @DonWillems,
Issue is resolved! :v:
