### ISSUE TITLE
Users: Restricted user (and other realm roles) can not be set and unneeded "," shown

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#781]
Replicate (see images of select field):
- Go to users page, open user
- Try to set restricted user (or any other realm role that shows up)
- Save user
- Open user to see if role is still selected. Its not.

Additionally, " , " is shown in the select field while it should show not realm roles are selected (although in keycloak the default roles and two roles every user should get are set)

![image](https://user-images.githubusercontent.com/14177035/182852727-969a8f5f-9c73-4dba-adfe-e17069141781.png)

**Comment by MartinaeyNL** [comment]
Seems to be failing after the Keycloak version update. Before that it works fine on my machine. (tested commit ec3a104dedadb7b3f68fe2e8941f168b86e97ed6)

**Comment by MartinaeyNL** [comment]
This is probably only an issue when editing a user, not present when creating a new one. (in my local deployment at least)
