### ISSUE TITLE
(Date)Time input: when setting a time (while in UTC+2), it changes to UTC

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#790]
Reproduce:
- Go to staging.demo.openremote.app
- Change the time in a history panel, or insights chart.
- Wait a second
- The time changes to two hours before set time (assuming you are in CEST)

Expected:
- To keep the time set in the input

Questions:
- What time is used to store attribute events in the database?
- Are we using the machines time zone? users time zone?
- Should we be able to set the time zone to use in the manager config?

**Comment by MartinaeyNL** [comment]
Have been able to reproduce this bug. Seems that `or-mwc-input` outputs the time in miliseconds in UTC.
Other components parse this into a date (not taking UTC into count), which results in weird behavior as you described.
Started working on a fix.

**Comment by MartinaeyNL** [comment]
Have been able to reproduce this bug. Seems that `or-mwc-input` is dispatching the incorrect time.
Investigating now.
