### ISSUE TITLE
Asset: disable view mode when not saved

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#797]
Reproduce:
- Add an asset while in modify mode
- Do not save
- Go to view mode 
- Asset view page is shown with some attributes (not all, e.g. for KNX)

Expected
- Add an asset while in modify mode
- Do not save
- View mode is disabled

**Comment by DonWillems** [comment]
I've tested locally with the view button disabled, but this doesn't feel right either.
This would be solved if we add the 'required attribute value' functionality to the add asset dialog. That way assets, whether in view or modify mode, will always be saved when clicking add in the dialog.
