### ISSUE TITLE
Insights (new): Issues

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#803]
- [x] When switching from 'Modify' to 'View mode. The widgets are empty and only displaying 'Widget is too small'. Resizing screen will make them appear again.
- [x] When dragging a KPI widget on the screen it's initially saying 'Widget is too small' in stead off 'No attributes connected'
- [x] Add write/read permission to roles to enable the 'edit the dashboard option'
- [x] When the widget is selected and the setting is viewed at the right, the realm picker is partially hidden behind the settings
- [ ] Warn users when navigating away from dashboard without saving their latest changes (eg. via top bar navigation, selecting a different dashboard, select an item from settings, or changing realms
- [ ] add duplicate dashboard function
- [x] First widget which get's added has a strange ID name
- [x] KPI widget doesn't show a selected attribute
- [x] Don't show: Modify button, link button and hamburger icon when no dashboard is selected (when navigating to Insights). Only show text 'Please select a dashboard on the left.' (no capital, same as on rules page)
- [ ] Hamburger icon should have same behaviour as copy URL icon: short flash of background when pressing, and background disappearing again.
- [x] Setting options: 'show value as' and 'decimals' are available for chart, while it should be available for KPI panels.
- [ ] When I create a 2nd dashboard and don't save it, I get a warning when navigating away. When I select 'Discard' I expect the dashboard to not show in the list on the left. 
- [ ] When I don't save a dashboard (Discard), navigate away to e.g. 'Assets' and come back to 'Insights' I still see the unsaved dashboard. I expect it to not be shown.
- [x] The title of a chart/KPI panel on the settings column is shown as 'title:'. Leave out the ':'.

29/9/22
- [x] Left Align 'My dashboards' with individual names
- [x] Delete option 'Who can view the dashboard' = Public for first version
- [x] Align Title of dashboard and 'back' arrow on mobile, similar as on assets page
- [x] Use same arrow icon as on asset page
- [x] Remove link button for first version
- [x] Add setting for KPI widget
- [x] Change number of columns, mobile screen behaviour, and 'mobile breakpoint' when pressing 'Set to mobile preset'
- [x] Remove + asset and dustbin in dashboard list for user with 'Insights read permission'

30/9/22
- [x] Sometimes the resizing option for widgets dissapears. It reappears when shift-refresh

3/10/22
- [x] When merging with master branch remember to add 'read/write insights' role to 'smartcity' user for demo.
- [ ] When user has no read access to Insights, he should see the list column without any dashboards listed, but text 'no read access' or no text at all. Note, behaviour of other topics is inconsistent: Map does show but without assets (correct), Asset list is shown but no assets are not shown (mentioning 'loading...' which should be 'no read access' or no text at all), Rules still shows list of all rules but no content of individual rules (should show in list 'no read access' or no text at all).
- [x] When creating a new dashboard, adding a KPI widget and selecting an attribute, it doesn't show in the KPI panel. Only when navigating to another widget or adding a second it shows. This doesn't happen when later coming back to the same dashboard...
- [x] The text labels 'second', 'hour', 'week', 'month' do not fit in the KPI panel. The last character is not completely visible.
- [x] The text labels for Timeframe always get shown as 'DAY' in view mode
- [x] The values and units in KPI panels should scale down on smaller devices so that they always fit within the panel.
- [x] When showing timestamp controls for a chart, by default show a single period
- [ ] When chart get's too small to show date input, only show left/right arrows
- [x] When you select 'Block this device' for the option 'on a mobile screen' align the text 'This dashboard doesn't support...' vertically in the middle (or similar as on asset page when no asset is selected)
- [x] Disable editing on mobile screens (when making screen smaller from desktop, when in modify mode)

KPI Widget:
- [x] When navigating to a dashboard and selecting a first KPI widget you see all settings including the selected attribute. When moving to another KPI widget, without closing the first KPI widget all the settings for the second panel change but the selected attribute of the second widget is not showing.
- [x] When reselecting an attribute for the second panel, the behaviour repeats: when going to the next panel, all settings change but no selected attribute is visible.
- [x] Increase space below 'My dashboards'

16/10/22
- [x] When adding a dashboard and changing the setting for mobile to 'keep layout' the save button remains grey
- [x] Gauge doesn't always fit vertically (see picture below)
- [x] Day and number setting don't always fit for KPI panel (see picture below)

Wish:
- [ ] add copy/paste/delete function for widgets

<img width="492" alt="Screen Shot 2022-10-16 at 15 14 04" src="https://user-images.githubusercontent.com/11444149/196037580-0d219c45-2bc8-4065-81fe-2774b3cabaf9.png">
<img width="797" alt="Screen Shot 2022-10-16 at 15 19 29" src="https://user-images.githubusercontent.com/11444149/196037790-7a097ef2-de99-4dcf-8056-0559de0ddd32.png">

18/10/22
- [x] KPI panel 'day' and ''percentage' get saved but are not shown (always shows 'day' and 'absolute')
- [x] Chart keeps white space on the right when no 'legend' or 'timestamp' controls.
- [x] icons and value are continuously switching size for KPI panel at specific dimension (see below)
![Screenshot 2022-10-18 at 10 12 52](https://user-images.githubusercontent.com/11444149/196374861-27d7c42e-c83f-4f1e-9f01-a0e09a10483e.png)

**Comment by pierrekil** [comment]
added a few more :-)

**Comment by pierrekil** [comment]
looks great, just a few more comments

**Comment by MartinaeyNL** [comment]
> "When adding a dashboard and changing the setting for mobile to 'keep layout' the save button remains grey"

**Comment by MartinaeyNL** [comment]
> When adding a dashboard and changing the setting for mobile to 'keep layout' the save button remains grey

Seems that this happens only on a few occasions. Mostly when after switching dashboards.
The issue is caused by the Material Design component (not even `or-mwc-input`, but in the `MDCSelect:change` event),
which does not detect any changes. So there is nothing we can do other than completely writing the selection logic ourselves.

**Comment by pierrekil** [comment]
Just leave as is (I closed the issue)

**Comment by pierrekil** [comment]
First Insights with dashboard editor introduced. Further improvements in #843
