### ISSUE TITLE
Insights: create Gauge widget

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#824]
The gauge widget shows the current value of one chosen attribute on a dial. It can only be used for numeric valuetypes. This gauge shows colors set by the user at threshold values. The attribute value, its asset type icon and color, and the unit is shown below the gauge.
A write permission user can set the thresholds used in the gauge widget on the Insights page widget settings.

Gauge settings:
- Min: the base value. Used as leftmost limit
- Max: the upper limit (fully to the right)
If the selected attribute value is higher or lower than these limits. The gauge pointer will be shown either fully to the right or left, and have its respective threshold colors.

Thresholds have:
- min: the value from which this range is valid. Up to the min of the 'next' threshold
- color: the color shown in the range of this threshold.

If a user tries to set a threshold value lower than the min of the gauge, it is not saved and shown as incorrect.

There is always a threshold for the minimum set on the gauge shown as "Minimum ([min value dynamically shown here])". Which has a green color by default (which can be changed). This threshold can not be deleted.

When adding the gauge to an Insights dashboard, it is added with two additional threshold values to help the user along (both color and value can be changed, they can also be deleted):
- Yellow with a value of 75
- Red with a value of 90

At the bottom of the threshold list is an "+ add threshold" button that adds a threshold value at the bottom of the list. This threshold has a value that is prefilled with the previous value +10, so that it starts at the bottom of the list by default. The value input field is focused when adding the threshold so that the user can immediately start typing.

**Comment by MartinaeyNL** [comment]
Basic component added in PR #742 , but I want to put a bit more effort making the `or-gauge` component more flexible to use.

**Comment by pierrekil** [comment]
Visual improvements added to #843 (not always showing full scale.
