### ISSUE TITLE
Asset page gets stuck on loading after an AssetEvent occurs

### ISSUE THREAD

**Issue by igorrutka** [openremote/openremote#835]
**Describe the bug**
When you import assets with the file selector the page stays on "Loading..."

**To Reproduce**
1. Create agent with file selector, for example Velbus Serial Agent
2. Upload assets from a compatible *.vlp file
3.  After a succesfull asset upload the page stays on "Loading..."

**Work around**
1. Click on a different asset
2. Go back to the agent with the file selector

**Expected behavior**
Agent page refreshes to normal state

**Screenshots**
![file selector loading issue](https://user-images.githubusercontent.com/107846439/195049488-10c0ced3-cfc3-4d7f-8315-49d8cbbd5068.png)

**Comment by richturner** [comment]
This issue is also reproducible when an asset is selected and then an `AssetEvent` occurs for this same asset the viewer gets stuck at the loading message.
