### ISSUE TITLE
Authentication login ForbiddenException

### ISSUE THREAD

**Issue by Fabrizio-de-Canha** [openremote/openremote#860]
Hi, I have followed the deployment instructions and all containers pull and start successfully.

Once opening my browser and trying to log in (with user: admin, password: secret) the manager loads in browser but there is no functionality.

The only error I see is in the manager container:

FINE    [WebService task-1             ] emote.container.web.WebServiceExceptions : Web service exception in 'RESTEasy Role Security' for 'GET http://localhost.com/user/user' type = ForbiddenException, message=Must be authenticated

It seems using an incorrect username and password yields the same error.

Any help will be appreciated.

**Comment by richturner** [comment]
These sorts of questions should be raised on the [forum](https://forum.openremote.io).

If you are running the full OpenRemote stack and you can login when requesting `http://localhost/manager/` can you please post on the forum the browser error(s) you receive (if any).
