### ISSUE TITLE
App: create location provider

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#861]
As a user I want an app to know my location, so that I can find myself on a map.

Add a location provider to iOS and Android apps. This provider should let the app get the location of the user while the app is open to show that location on a map/center on that location.
The additional request that is in the app now to get the location while the app is in the background should not be present for the location provider.

This in addition to the geofence provider that compares location to an area and requests the app to get the location also in the background.

- [ ] Android generic app, doesn't allow navigating to own location. Own location is not shown.

**Comment by pierrekil** [comment]
Android generic app, doesn't allow navigating to own location. Own location is not shown.

**Comment by pierrekil** [comment]
replaced by #958
