### ISSUE TITLE
Rules: incorrect behaviour related to realms as admin user

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#875]
When logged in as an admin user you should be able to see the rules in each realm, but only of the realm you are in. You should also be able to see the assets of other realms while creating a global rule. You should not be able to see assets of other realms while creating a realm rule.

Bugs:
- [x] As admin user I can access assets from another realm while creating a realm rule. Expected: only see assets of the realm I'm in.
- [x] As admin user when I start creating a rule, switch realms, and save it, it is saved in the realm where it was 'created'. Expected: When switching trigger discard dialog, or if not possible empty the page/deselect rule.
- [x] Rules list does not show correct rules when switching back and forth between realms (only in case of Master realm?)

**Comment by MartinaeyNL** [comment]
> As admin user when I start creating a rule, switch realms, and save it, it is saved in the realm where it was 'created'. Expected: When switching trigger discard dialog, or if not possible empty the page/deselect rule.

I was not able to show the discard dialog, since there is no easy way to "cancel" or block the realm switching.
It now simply erases your changes immediately.
