### ISSUE TITLE
Appearance - build fail (favicon.)

### ISSUE THREAD

**Issue by DasAuryn** [openremote/openremote#897]
**Describe the bug**
If you uploaded a custom favicon.ico to the configuration site (Appearance) and build gradlew clean installDist, there appears an issue, because gradlew can't copy the ico file.

```
Execution failed for task ':deployment:installDist'.
> Could not copy file 'C:\Users\************\Documents\OpenRemote\openremote\deployment\manager\app\images\default\favicon.' to 'C:\Users\*************\Documents\OpenRemote\openremote\deployment\build\image\manager\app\images\default\favicon.'.
   > Problems opening file input stream for file: C:\Users\**********\Documents\OpenRemote\openremote\deployment\manager\app\images\default\favicon.
```

**To Reproduce**
1. upload a new favicon.ico to the configuration site
2. gradlew clean installDist

**Comment by NealGeilen** [comment]
Hi, Thx for reporting this bug. 

Could you tell me what mime type the image has that you uploaded? as a favicon.

**Comment by DasAuryn** [comment]
Hi Neal,

you're welcome.

it was: image/x-icon
