### ISSUE TITLE
Websockets not supported on mobile iron

### ISSUE THREAD

**Issue by milovanderlinden** [openremote/openremote#92]
When the Border Control App is moved inside the hardened infrastructure for KMAR, [Mobile Iron](https://www.mobileiron.com/) will provide the webbrowser on any of the legitimate devices use by personel. One of the caveats of Mobile iron is that it does not support websockets. For our other application we run into the same issue. We are currently investigating what protocol can be used as a work around; long polling, jsonp or others. Once we get the results in, I will provide the details so you can adapt.

**Comment by richturner** [comment]
Removed as this is specific to a custom project and shouldn't be mentioned in main repo
