### ISSUE TITLE
Easy way to change map to another city?

### ISSUE THREAD

**Issue by Deputy-Chief-Hardy** [openremote/openremote#944]
Hi, I wanted to use OpenRemote with the map of Berlin city. Is there an easy way to change this? I downloaded the map already from https://openmaptiles.com/downloads/. Afterwards I am lost, I do not really get the steps here: https://github.com/openremote/openremote/wiki/Developer-Guide%3A-Working-on-maps
Appreciate any help! Cheers

**Comment by richturner** [comment]
Hi, this is something for the forum, maybe this thread or start a new one:

https://forum.openremote.io/t/change-the-map-in-the-manager-ui/709/6

You need to set the `OR_MAP_TILES_PATH` environment variable on the manager container to some path within the manager container that you volume map to your own `mbtiles` file.
