### ISSUE TITLE
Console Android: center on map

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#958]
Reproduce:
- App settings set to allowing location.
- Go to iEMS via Android 
- Go to asset page and modify location of the asset
- Center button on map, doesn't move map to my location.

Expected: 
- See and move to my location when pressing center button

Reproduce:
- App settings NOT set to allowing location.
- Go to iEMS via Android 
- Go to asset page and modify location of the asset
- Center button on map, doesn't move map.

Expected:
- App should ask permission to use location.

**Comment by Miggets7** [comment]
@pierrekil What is the IEMS url?

**Comment by pierrekil** [comment]
How is this solved? On mobile you can't change asset location (my mistake). But center button on the main map, with current Android console doesn't center to my location (using iEMS).

**Comment by Miggets7** [comment]
I need to update the generic app
