### ISSUE TITLE
New Keycloak UI (based on webcomponents)

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#97]
- [x] When trying forgot password flow, I get error when submitting username. 
- [ ] When typing wrong user, the result visually looks incorrect.

**Comment by richturner** [comment]
The first issue is because of incorrect environment variables for setting up email server to allow keycloak to send emails

**Comment by richturner** [comment]
I will update the profiles to resolve this

**Comment by richturner** [comment]
Second issue is a styling/rendering problem which I will fix shortly
