### ISSUE TITLE
Insights: Widgets move when going from view to edit mode

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#982]
Reproduce:
- Add chart or map widget to a board (and other widgets)
- Select asset attributes for either
- Save and go to view mode
- Go back to edit mode
- Widgets are moved (appears to be down the height of the node)

Expected:
- Widgets stay in place

Investigation:
- grid.on change event only takes place when chart or map have data in them. That event sets the grid.y to the node.y, which is not correct. The event should not be needed as nothing changed, you just went to edit mode. **Same for the 'reload' button**
- The setupGrid is run multiply times when either switching to edit mode or pressing the 'reload' button.

**Comment by DonWillems** [comment]
@MartinaeyNL to clarify, this is the event I was talking about where I see an incorrect node.y being use to create the template: https://github.com/openremote/openremote/blob/83a4d9ddde8f52220c1929846e3bbd0b2bf7865d/ui/component/or-dashboard-builder/src/or-dashboard-preview.ts#L396

**Comment by MartinaeyNL** [comment]
Solved by overriding gridstack.js logic using GridStackEngine.
Apparently during some rerenders it collided with an old instance of the widget.
So now checking whether the collided widget has the same ID. If so, cancel the movement.

See `or-dashboard-engine.ts`
