### ISSUE TITLE
Insights: Widgets responsive styling

### ISSUE THREAD

**Issue by MartinaeyNL** [openremote/openremote#988]
Currently widgets behave somewhat weird when they are small. We want to improve this for some widgets by disabling certain elements.

**KPI Widget**
- [x] When widget becomes smaller:
  - first step: reduce font size of value and unit until same size as title (not smaller)
  - and reduce font size of timeframe and align on right (not falling out of sight)
  - and reduce font size of value change and align on right (not falling out of sight)
  - next step: remove icon
  - next step: remove graph/period/change per period (so only show value)
- [x] resolve glitches/bugs showing element outside borders of widget, (see below).
- [x] When no attribute is connected: "No attribute connected", not plural. 

**Gauge**
- [x] When widget becomes smaller
  - first step: scale gauge to fit the widget (now cut off)
  - and reduce font size of value and unit until same size as title (not smaller)
  - next step: remove icon
  - next step: remove value (so only show gauge)
- [x] When no attribute is connected: "No attribute connected", not plural.

**Chart**
- [x] Set default time period to 'LAST 24 HOURS'

The approach should be similar to the one in `or-chart`, where an `ResizeObserver` listens for changes
and then applies the correct styling to the element.
![Screenshot 2023-03-27 at 11 58 19](https://user-images.githubusercontent.com/11444149/227909236-df6d4c67-07b2-4c5b-a5af-20fd899bea81.png)

**Comment by pierrekil** [comment]
Also see #843 for specifications

**Comment by MartinaeyNL** [comment]
Some of the completed tasks, such as the Gauge and Chart fixes, are included in PR #994
